### ISSUE TITLE
串接成功並運行一天後，接收到 Request failed with status code 429

### ISSUE THREAD

**Issue by zzz67240** [memochou1993/gpt-ai-assistant#10]
各位前輩好
我昨日串接都成功，可以對話，並將機器人分享與朋友們使用，目前約29人使用。
然後今日早晨一開始是收不到回傳訊息，我Redeploy後，在LINE聊天對機器人發送訊息，收到回覆Request failed with status code 429。
看起來用量應該未達上限？還是說要像這條裡面的一樣，先設定payment?
https://github.com/memochou1993/gpt-ai-assistant/issues/2

![image](https://user-images.githubusercontent.com/9304174/207207545-8a69c128-56f7-47e7-ab5e-bb7749531f8d.png)
![image](https://user-images.githubusercontent.com/9304174/207208069-e913dcb1-061b-45e2-9fab-614c6e2bb090.png)

**Comment by adat-will** [comment]
我解決的方法是不設置 `LINE_API_SECRET ` 的環境變數.... 就可以運行了

**Comment by zzz67240** [comment]
我原本沒設置 LINE_API_SECRET，昨天可以運行，今天無法。
然後我剛剛嘗試把LINE_API_SECRET 加上去，redeploy，一樣429。
再次拿掉，redeploy，還是429。

**Comment by memochou1993** [comment]
@zzz67240

嗨，加入多人群組比較容易發生 429 過多請求的問題，因為 OpenAI API 是有請求速限的

建議兩個方法：

1. 讓它清淨一會兒
2. 用 https://github.com/memochou1993/gpt-ai-assistant/issues/2 的方式解決

另外還有 https://github.com/memochou1993/gpt-ai-assistant/issues/5 這題，功能實作後可能可以改善

**Comment by memochou1993** [comment]
@adat-will 

嗨，加上 `LINE_API_SECRET` 應該要可以運作，有機會再幫我試試

這是為了驗證請求來自 LINE 官方，可以避免受到惡意請求

**Comment by zzz67240** [comment]
問題點找到了，結果並非技術問題。
如果串接都OK，Webhook有掛到且Vercel查看發送的請求是成功的，那有可能是因為Open AI的usage quota已盡。
![image](https://user-images.githubusercontent.com/9304174/207227819-d4022d0f-c3fd-4631-878a-237900550e4d.png)
