### ISSUE TITLE
Shows Error Message on verifying Webhook URL

### ISSUE THREAD

**Issue by Sniper711** [memochou1993/gpt-ai-assistant#11]
Shows Error Message on verifying Webhook URL. Did this ever happen to you?
![截圖 2022-12-13 at 3 45 29 PM](https://user-images.githubusercontent.com/17037569/207257136-355f99a4-2f3e-404f-8bd1-10c6f8a5d936.jpg)

Error
The webhook returned an HTTP status code other than 200.(404 Not Found)

Confirm that your bot server returns status code 200 in response to the HTTP POST request sent from the LINE Platform. For more information, see [Response](https://developers.line.biz/en/reference/messaging-api/#response) in the Messaging API Reference.

**Comment by memochou1993** [comment]
@Sniper711 

Hi,

Please check the webhook URL must be suffixed with `/webhook`.

**Comment by ha168156** [comment]
hello 
我一樣在
https://gpt-ai-assistant-ha168156.vercel.app/webhook
也是出現200回應錯誤
