### ISSUE TITLE
設定環境變數 OPENAI_COMPLETION_MAX_TOKENS 後，會收到 Request failed with status code 400

### ISSUE THREAD

**Issue by superdhuang** [memochou1993/gpt-ai-assistant#12]
設了環境變數後有問題，看起來是當成string丟出去了??

丟出的payload會變下面這樣:
data: '{"model":"text-davinci-003","prompt":"A: undefined\\nQ: ai 你好？\\n","temperature":0.9,"max_tokens":"400","frequency_penalty":0,"presence_penalty":0.6,"stop":[" A:"," Q:"]}'
    },
<img width="936" alt="issue" src="https://user-images.githubusercontent.com/1615542/207312510-4da414ac-02b2-4feb-a906-af2e8428cb39.png">
其他數值的環境變數應該也有一樣的問題??

**Comment by memochou1993** [comment]
@superdhuang 

感謝回報！我來修正！

**Comment by memochou1993** [comment]
@superdhuang 

已修正數值類型的環境變數！
