### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by jhihyulin** [memochou1993/gpt-ai-assistant#120]
```
[POST] /webhook
09:03:04:16
Function Status:
500
Edge Status:
500
Duration:
433.97 ms
Init Duration:
N/A
Memory Used:
146 MB
ID:
hnd1::hnd1::c5t2f-1673398984158-cb87ae75fa34
User Agent:
LineBotWebhook/2.0
2023-01-11T01:03:04.613Z	c8d2788a-67c1-44a5-9372-09b47e00064d	ERROR	Request failed with status code 404
2023-01-11T01:03:04.613Z	c8d2788a-67c1-44a5-9372-09b47e00064d	ERROR	{ error: { code: 'NOT_FOUND' } }
```
![chrome_screenshot_2023年1月11日 上午9_08_46  GMT+08_00](https://user-images.githubusercontent.com/74854953/211694578-a3bc7948-7f35-48dd-ad7e-e355c272c34e.png)

![chrome_screenshot_2023年1月11日 上午9_10_30  GMT+08_00](https://user-images.githubusercontent.com/74854953/211694797-6580511e-b7e8-4008-a715-6c8bd802a9e4.png)

**Comment by g0930270892** [comment]
我遇到一樣的錯誤訊息，但Vercel 專案名稱與 GitHub 專案名稱似乎設定一樣
![1678036229684](https://user-images.githubusercontent.com/127033325/222975236-d92f4284-93e6-4982-82af-2e1dfbe4c5eb.jpg)

**Comment by memochou1993** [comment]
@g0930270892 

請從頭操作一遍喔！
