### ISSUE TITLE
English Chat

### ISSUE THREAD

**Issue by NiyashoChan** [memochou1993/gpt-ai-assistant#123]
Followed the instructions on [https://dev.to/memochou1993/chat-with-ai-using-line-app-6o5](https://dev.to/memochou1993/chat-with-ai-using-line-app-6o5). It works in Chinese so I added **OPENAI_COMPLETION_INIT_LANG**: **en** within the Environment Variables on vercel.com and redeployed. 

ChatGPT still answers in Chinese within LINE. What is wrong?

**Comment by memochou1993** [comment]
@NiyashoChan 

Hi!

Thanks for your feedback.

Please check the latest [documentation](https://github.com/memochou1993/gpt-ai-assistant/blob/main/README.en.md#environment-variables) here!

The post on dev.to is also updated!

**Comment by NiyashoChan** [comment]
Works perfectly! THANK YOU
