### ISSUE TITLE
希望可以畫圖功能串接 Midjourney

### ISSUE THREAD

**Issue by nightmare9983** [memochou1993/gpt-ai-assistant#124]
希望可以畫圖功能串接Midjourney，

目前畫圖有時候不會有圖片，

例如 : 畫一隻皮卡丘

**Comment by memochou1993** [comment]
@nightmare9983 

看起來不錯，我來研究一下。

**Comment by memochou1993** [comment]
目前 Midjourney 還沒有提供開放 API 出來給人使用，這張票先關閉。

謝謝建議。
