### ISSUE TITLE
連線超時：timeout of 9000ms exceeded

### ISSUE THREAD

**Issue by billxu0521** [memochou1993/gpt-ai-assistant#126]
最近使用常出現timeout of 9000ms exceeded 

看起來是因為與v1/completions這支api溝通時超過9000ms
想問一下其他人有沒有遇到類似狀況？

想到兩個調整方向：
1.使用者輸入訊息後，等待時的回饋
2.延長與api溝通的等待時間

**Comment by billxu0521** [comment]
補充  感覺openAI的api最近回應也有點變慢
在playground到沒這種感覺

**Comment by memochou1993** [comment]
這個問題可能暫時無解

不過可以修改更親切一點的文案就是了

**Comment by yuliang615** [comment]
同感不過可以在services line.js open.js裡修改timeout 數值，不知道有沒有用

**Comment by memochou1993** [comment]
@yuliang615 

主要是 Vercel 免費方案會有 10 秒超時限制，所以現在 Axios 超時限制都設定 9 秒～

**Comment by yuliang615** [comment]
所以除非付費購買 不然無法解決？

**Comment by billxu0521** [comment]
感謝回應，我懂問題了qq 

主因是要等GPT回應，時間很難預期，如果要他提供長文本答案應該很容易超過10s
Vercal免費版本的執行時間是10s  Pro是60s  企業版是900s
Pro的60s的確夠

這邊是參考資料
https://vercel.com/docs/concepts/limits/overview

**Comment by memochou1993** [comment]
沒錯，就是 @billxu0521 補充的這樣。

新增了 2.2.0 版，若發生超時，會出現 `重試` 指令按鈕，然後加上了中文的錯誤訊息。

不過對於長文本，不管怎樣重試，都有可能超時就是了。

這 10s 算是個硬限制。

**Comment by yuliang615** [comment]
如果不使用vercel使用其他的網站呢？

**Comment by memochou1993** [comment]
可以研究看看有沒有類似的託管服務沒有超時限制哦！

像是我自己在用的 Linode 就沒有這個限制，不過我有付費就是了。

**Comment by memochou1993** [comment]
有想到方法了，我研究一下，先重新開啟這張票。

**Comment by yuliang615** [comment]
請問是要將Vercel 換成別的嗎

**Comment by memochou1993** [comment]
嗯，這個專案畢竟依賴 Vercel 免費專案，有其局限性。

之後應該會開一個新的專案來做。

**Comment by Ayesy** [comment]
提醒 LINE messagingAPI 免費的只有500則可以使用哦
另外要開啟能夠加群組，才可以加入與群組聊天。
Line「社群」則不能加入

**Comment by memochou1993** [comment]
@Ayesy 

我記得不用費用吧？

Reply API（自動回覆訊息）：指 LINE 機器人針對 LINE 用戶傳來的訊息進行自動回覆的 API，屬於「不列入計價的訊息」。

Ref: https://tw.linebiz.com/column/budget-auto-count/

**Comment by memochou1993** [comment]
關於超時，目前的架構下除非付費，不然無法解決，這張票先關掉。

參考常見問題：

https://memochou1993.github.io/gpt-ai-assistant-docs/questions.html

**Comment by memochou1993** [comment]
@billxu0521 @yuliang615 

解掉囉！

更新到 v4 的話，預設是 ChatGPT API 了，回應速度超快！

**Comment by billxu0521** [comment]
稍早更新試過了，今日3.5升級有感

感謝各位持續更新！
