### ISSUE TITLE
Request failed with status code 401

### ISSUE THREAD

**Issue by harkno1** [memochou1993/gpt-ai-assistant#128]
![IMG_7553](https://user-images.githubusercontent.com/26177548/216760966-a560f479-a34d-44c4-94ee-40088f190ce3.jpg)

進入對話一直出現附圖訊息！

**Comment by memochou1993** [comment]
@harkno1 

嗨，請重新產生一個 Open AI 的 API Key 並重新部署哦！

**Comment by Tsungyu-Ho** [comment]
您好，我已經重新佈署多次Open AI 的 API Key，但依然顯示Request failed with status code 401 ，請問可以怎麼做?OPEN AI 中API KEY 的 LAST USED 一直呈現Never

**Comment by memochou1993** [comment]
@Tsungyu-Ho

1. 刪除現在的 key 並重新產生一個
2. 刪除 Vercel 上的環境變數，重新填寫 `OPENAI_API_KEY` 和 key，注意不可參雜空白
3. 重新填寫後，重新部署

再試試看吧！
