### ISSUE TITLE
There are too many post failed.

### ISSUE THREAD

**Issue by anson999** [memochou1993/gpt-ai-assistant#129]
16:47 Android粉愛聊 Request failed with status code 429
16:47 Android粉愛聊 POST https://api.openai.com/v1/completions
16:47 Android粉愛聊 The server had an error while processing your request. Sorry about that!

![image](https://user-images.githubusercontent.com/42862625/217993230-e4b5e199-2a4e-4b3f-a441-34a0d27e8bf8.png)

**Comment by memochou1993** [comment]
@anson999 

請問發生的頻率是怎樣？

我在想有可能 OpenAI 系統超載。
