### ISSUE TITLE
可否新增環境變數，控制初始的機器人的自動回覆是開啟或是關閉？

### ISSUE THREAD

**Issue by aceonaceon** [memochou1993/gpt-ai-assistant#131]
不知道有沒有辦法預設就是關閉自動回覆呢？我自己測試一下，新的人跟官方號開始一對一對談，本來前一個對話已經關閉自動回覆了，但是新的人來開啟另外一個一對一對談，新的人就會是開啟自動回覆，但是前一個一對一對話仍然是關閉的。所以想說是不是可以新增一個環境變數，是在deploy時就決定預設自動回覆是開啟或是關閉？

**Comment by memochou1993** [comment]
感謝建議！

我來研究看看，應該是可以的。

**Comment by memochou1993** [comment]
@aceonaceon 

嗨，我想確認一下你的情境應該和群組無關對吧？

不過我覺得當一個加入了 AI 好友，應該預設是會希望 AI 主動回話才對？

**Comment by LuAdolph** [comment]
群組是不是不適合？
我有看到有人把他加到群組就很吵
大家講一句 AI 就要講一句=.=

**Comment by memochou1993** [comment]
@LuAdolph 

可以關閉自動回覆，透過呼叫 AI 的名字對話哦！

**Comment by memochou1993** [comment]
有問題再提出，此票先關閉。

**Comment by aceonaceon** [comment]
> @aceonaceon
> 
> 嗨，我想確認一下你的情境應該和群組無關對吧？
> 
> 我覺得當一個人加入了 AI 好友後，應該是會預設希望 AI 主動回話才對？
> 
> 可以討論一下。

對，確實不是在群組的使用場合。是在Line官方號一對一的對話時，我的使用場景是官方號一對一對話還是有真人服務。所以新加入官方號的人，預設就會一直收到AI的回應，除非他懂得自己關掉。所以會希望使預設關閉，讓加官方號的人，呼叫AI的名字才能讓AI回應

**Comment by memochou1993** [comment]
了解，我把票開起來。

**Comment by aceonaceon** [comment]
> 
感謝您

**Comment by memochou1993** [comment]
@aceonaceon 

嗨，新增了一個 `BOT_DEACTIVATED` 環境變數，設置為 `true` 表示要在一開始將自動回覆設為關閉，新增後需重新啟動。

對了，這只會在新用戶身上生效，如果你希望舊用戶也生效，需要把 `APP_STORAGE` 環境變數刪除。

**Comment by aceonaceon** [comment]
> 

感謝您快速的更新！
