### ISSUE TITLE
缺少環境變數 VERCEL_ACCESS_TOKEN 

### ISSUE THREAD

**Issue by vinci9527** [memochou1993/gpt-ai-assistant#132]
LINE使用關閉自動回覆指令時 顯示缺少環境變數 VERCEL_ACCESS_TOKEN 
但是VERCEL上無法新增此變數的TOKEN，不知有沒有方法可以新增此環境變數

**Comment by memochou1993** [comment]
@vinci9527

嗨！

試著先新增專案，新增完再到設定頁添加 `VERCEL_ACCESS_TOKEN` 環境變數。
