### ISSUE TITLE
優化 ChatGPT 聊天機器人

### ISSUE THREAD

**Issue by Dayu0815** [memochou1993/gpt-ai-assistant#133]
是否將可以透過網頁擴展功能的方式，在詢問 ChatGPT 聊天機器人問題之前，先向 Google 大神搜尋相關的資料，結合 ChatGPT 與 Google 搜尋，藉此突破現有僅能整理學習 2021 年以前資料的限制呢…？

**Comment by memochou1993** [comment]
@Dayu0815 

嗨！我不是程序猿哦。

這題我可以研究看看，感謝提供新點子！

**Comment by memochou1993** [comment]
@Dayu0815 

嗨。

請升級到 v3.0.0 試試看，需要去 [SerpApi](https://serpapi.com/) 網站建立一把 API Key，並到 Vercel 添加 `SERPAPI_API_KEY` 變數使用。

指令是「查詢」，比方說「查詢台積電股價」、「查詢信義區天氣」等。

不過壞消息是，SerpApi 一樣是有使用額度的，而且沒有很多。

**Comment by Dayu0815** [comment]
@memochou1993 
感謝您的回覆：
是發現目前的狀況，主要等候GPT回應，時間很難預期，過於複雜問題，需要提供長文的答案，很容易超過10s，然後，目前也難突破現有僅能整理學習 2021 年以前資料的限制，是希望能儘量找到在免費的架構上，做出較完整搜尋範圍，比較貼近網路版聊天的狀況

**Comment by memochou1993** [comment]
@Dayu0815 

了解，只是目前超時的問題，在 Vercel 的架構（免費方案）下似乎沒辦法解決。

之所以設計要用「查詢」指令，是因為搜尋 Google 的 API 有額度，然後把查詢結果送給 AI 也會增加成本，因為字數變更多了。不過這是個很好的點子，感謝建議。

目前正在規劃一個新的專案，希望達到一樣的功能，但是可以解決超時的問題。

**Comment by Dayu0815** [comment]
@memochou1993
感謝您的回覆：
期待您的新專案，也期待微軟公司的 AI聊天機器人Bing、Google公司的AI對話機器人Bard，都能夠有好的改善方案，謝謝！

**Comment by memochou1993** [comment]
@Dayu0815 

感謝支持本專案～

**Comment by VicKuo0516** [comment]
ChatGPT回覆在Line裡面會被截掉不完整, 請問是哪邊有問題?

**Comment by memochou1993** [comment]
@VicKuo0516 

請開啟一個新的 issue 發問此問題，謝謝。
