### ISSUE TITLE
「連線超時，請重試。」狀況

### ISSUE THREAD

**Issue by CarolLiuXQ** [memochou1993/gpt-ai-assistant#136]
<img width="270" alt="image" src="https://user-images.githubusercontent.com/85448533/218313640-0f748527-2e5b-43fa-bf96-aa7bfecb201f.png">
如果問比較複雜的問題的話，都會出現「連線超時，請重試。」的回覆，這個和timeout of 9000ms exceeded 狀況 #126 是一樣的嗎?

**Comment by memochou1993** [comment]
@CarolLiuXQ 

嗨，一樣的哦。

先在同一串追蹤，此票關閉。
