### ISSUE TITLE
無法重設群組數，需不斷增加 APP_MAX_GROUPS

### ISSUE THREAD

**Issue by 8807p3** [memochou1993/gpt-ai-assistant#138]
已經退出的群組, 似乎在群組數不能消失,  不知道  有沒有辦法在 restart 後, 重新計算群組數,  有活動的群組才列入計算.

**Comment by memochou1993** [comment]
@8807p3

感謝回饋。

以目前的架構來說，要做這個功能似乎有點困難，因為沒有一個介面來管理它。

簡單的方式是清空所有已註冊的群組，方式如下：

到 Vercel 的環境變數，將 `APP_STORAGE` 的值，設置為 `{}`，套用後重新啟動。
