### ISSUE TITLE
機器人已讀不回 <ERROR Invalid character in header content ["Authorization"]>

### ISSUE THREAD

**Issue by coastk05396** [memochou1993/gpt-ai-assistant#139]
# 機器人已讀不回

### 1.環境變數 再三確認沒有錯誤
![errer2](https://user-images.githubusercontent.com/99809489/218908209-bc67de34-b4f5-4748-9f36-34fda06d4293.png)
---

### 2.OPEN AI 掛上信用卡 <也有嘗試著開第2個新帳號 API串 >
![error4](https://user-images.githubusercontent.com/99809489/218908238-3539586f-8863-4f5a-b789-f5ba3658f8c1.png)
---

### 3.webhook 已經顯示 **SUCCESS**
![error1](https://user-images.githubusercontent.com/99809489/218907315-6453aaaf-7a95-44e7-827f-c58832d823a4.png)
---

### 4.佈署到VERCEL 也是成功 
![error5](https://user-images.githubusercontent.com/99809489/218910298-15b5bf4b-f9e2-411b-b6cf-4d78f6306fc7.png)
---

### 5. Function Realtime log 錯誤訊息是  如以下圖片
<ERROR	Invalid character in header content ["Authorization"]>
![error6](https://user-images.githubusercontent.com/99809489/218910747-12da8b64-d72b-4e36-b352-24149f9c216d.png)
---

### 6.機器人 **已讀不回**
![error3](https://user-images.githubusercontent.com/99809489/218908437-6166c52c-9a97-4cd7-af35-b679bbb8b994.png)

**Comment by coastk05396** [comment]
@memochou1993 

帥哥好,  我剛剛已經放新的OPEN API KEY 換了兩次也重新佈署兩次 還是不行，
想請教一下 因為我在vercel 上project名字是 gpt-ai
我是否要去 VERCEL +一個環境變數  
VERCEL_PROJECT_NAME: gpt-ai-assistant ?

**Comment by coastk05396** [comment]
@memochou1993 

## 帥哥好, 剛剛全部把3個API 重用 現在是以下這樣 VERCEL Function Log 已經沒有error
![no error](https://user-images.githubusercontent.com/99809489/218925593-fc11d0a9-79d2-4817-8abb-dfea59c966c4.png)

### LINE 機器人也會說話了  但是它會回 <ERROR Invalid character in header content ["Authorization"]>
![error7](https://user-images.githubusercontent.com/99809489/218925599-0e13379c-9df4-488c-b4a7-c34fc64e4485.png)

### 能否求解? 謝謝@

**Comment by coastk05396** [comment]
@memochou1993 

我成功解決了 最後把 VERCEL_PROJECT_NAME 改成我 VERCEL專案的名字 成功了!

**Comment by coastk05396** [comment]
謝謝指點!

**Comment by memochou1993** [comment]
@coastk05396 

哇，聰明！

**Comment by coastk05396** [comment]
@memochou1993 

大大回報一個錯誤,
如果今天在VERCEL 上 專案設定別的名稱(不是用你預設的)， 在加入VERCEL_ACCESS_TOKEN環境變數的時候，重新佈署完。 webhook 那邊會出現500 server error 錯誤

**Comment by memochou1993** [comment]
@coastk05396

感謝回報，目前這是已知問題，發生在最早期，所以比較難透過 LINE 告訴使用者。
