### ISSUE TITLE
可設定語言(或國家地區)嗎？

### ISSUE THREAD

**Issue by delphinuz** [memochou1993/gpt-ai-assistant#140]
您好，

目前好像只能用繁體中文，即使以英文詢問，回筈還是中文。

可以設定為回覆是英文或其他語言嗎？

謝謝

**Comment by memochou1993** [comment]
@delphinuz 

請參考[環境變數](https://github.com/memochou1993/gpt-ai-assistant#%E7%92%B0%E5%A2%83%E8%AE%8A%E6%95%B8)，將 `APP_LANG` 設置 `en`。
