### ISSUE TITLE
有關Timeout問題

### ISSUE THREAD

**Issue by xljeff** [memochou1993/gpt-ai-assistant#141]
已經設定了 VERCEL_TIMEOUT / OPENAI_TIMEOUT 為 20000 , 並重新佈屬新的版本, 也將Line webhook指定到新的唯一版本, 但仍然在該版本的 Vercel 上看到log 【Task timed out after 10.01 seconds] , 是否有什麼需要注意的地方 ?

---已下為已加入之 Environment Variables
APP_MAX_GROUPS
Development, Preview, Production

OPENAI_TIMEOUT
Development, Preview, Production

VERCEL_ACCESS_TOKEN
Development, Preview, Production

APP_MAX_USERS
Development, Preview, Production

LINE_CHANNEL_SECRET
Development, Preview, Production

LINE_CHANNEL_ACCESS_TOKEN
Development, Preview, Production

OPENAI_API_KEY
Development, Preview, Production

**Comment by xljeff** [comment]
抱歉有看到前面相關資訊對於 Vercel 免費版本10秒鐘的限制, 所以應該不是參數問題, 我自行關閉ticket

**Comment by memochou1993** [comment]
@xljeff

是的，這部分很可惜。
