### ISSUE TITLE
未設環境變數 Max User ，但是會回報用戶數量已達上限

### ISSUE THREAD

**Issue by keanuhsieh** [memochou1993/gpt-ai-assistant#142]
之前是有設 Max Group，現在先把這個變數刪除重新 deploy 試試看

**Comment by memochou1993** [comment]
試試看，有問題再提供截圖，謝謝。

**Comment by keanuhsieh** [comment]
還是一樣，我重新加設 APP_MAX_USERS ，值 先設為 1000 試試
但我想請教一下，這個環境變數刪除是不是等於無限？

**Comment by memochou1993** [comment]
@keanuhsieh 

刪除等於無限沒錯，可以不設。
