### ISSUE TITLE
增加群組中是否重試的變數

### ISSUE THREAD

**Issue by 8807p3** [memochou1993/gpt-ai-assistant#145]
因為GPT 使用太熱門, 常常重試還是沒有用.   ,當bot 在群組中時,  一直跳出 連線逾時,很干擾對話的樂趣.
可以新增一個變數設定  讓 Line bot owner 設定  time out 時,  可以不給回應.  
 但如果user 想要 重試, 可用打字"重試" ,進行重試.

而一對一對話則不受影響.

.

**Comment by memochou1993** [comment]
@8807p3 

嗨。

版本 2.5.1 新增了一個 `ERROR_TIMEOUT_DISABLED` 變數，把它設成 `true` 會關掉超時錯誤，再試試看，謝謝。
