### ISSUE TITLE
設定 VERCEL_ACCESS_TOKEN 錯誤

### ISSUE THREAD

**Issue by Ayesy** [memochou1993/gpt-ai-assistant#149]
我在vercel專案裡的環境變數VERCEL_ACCESS_TOKEN 設定為我account產生的vercel APIkey
但是Line就會產生錯誤（如圖），請問該從哪個方向解決呢？謝謝
![截圖 2023-02-21 下午1 50 56](https://user-images.githubusercontent.com/16485501/220258771-04bc0206-f588-4a32-9339-092cd20a9dfb.png)

**Comment by Ayesy** [comment]
![截圖 2023-02-21 下午1 52 15](https://user-images.githubusercontent.com/16485501/220259051-b8d4a4c7-ad9e-4ea5-bec0-33a2d70232d3.png)
VERCEL_ACCESS_TOKEN的值我設定null 跟personal account generate 的API key Line裡面都連不上。

**Comment by s6601** [comment]
取得永久token設定VERCEL_ACCESS_TOKEN,就會報錯一樣的內容,取消及正常

**Comment by Ayesy** [comment]
我也還是沒有解決，可能我再重新做一次會不會好。
