### ISSUE TITLE
Webhook setting error

### ISSUE THREAD

**Issue by LucyLin0612** [memochou1993/gpt-ai-assistant#150]
在設定webhook時出現了error

Error
The webhook returned an HTTP status code other than 200.(308 Permanent Redirect)

Confirm that your bot server returns status code 200 in response to the HTTP POST request sent from the LINE Platform. For more information, see [Response](https://developers.line.biz/en/reference/messaging-api/#response) in the Messaging API Reference.

請問是哪裡有問題？

**Comment by memochou1993** [comment]
@LucyLin0612 

請問你的 URL 長怎樣？有沒有加上 `/webhook` 的結尾呢？
