### ISSUE TITLE
按照教學安裝，首頁出現 404: NOT_FOUND

### ISSUE THREAD

**Issue by arguskao** [memochou1993/gpt-ai-assistant#16]
https://health-line-bot.vercel.app/

不知道可能是哪裡錯了？

謝謝！

**Comment by memochou1993** [comment]
@arguskao 

嗨！請幫我檢查 Webhook URL 是否有用「/webhook」結尾。

請提供更多線索，謝謝。

**Comment by ys5603** [comment]
請問在line developers的webhook settings中，verify "https://gpt-ai-assistant-XXXXX.vercel.app/webhook" 會出現 403 Forbidden 錯誤，該在哪裡修正？謝謝

**Comment by arguskao** [comment]
> @arguskao
> 
> 嗨！
> 
> 你是不是在 Vercel 匯入到 https://github.com/arguskao/HealthLineBot 專案了？
> 
> 要匯入的專案是 https://github.com/memochou1993/ai-assistan 才對，先幫我 Star & Fork 一下。
> 
> 然後 Webhook URL 記得用「`/webhook`」結尾。

果然是匯入錯了...
我有star了喔！ 這麼棒的東西怎麼可以不star，還想多幾顆.

**Comment by ys5603** [comment]
> @ys5603
> 
> 嗨，請檢查 `LINE_API_SECRET` 是否填寫正確。

完成了！感謝協助～

**Comment by arguskao** [comment]
https://gpt-ai-assistant-arguskao.vercel.app/

我重新裝，https://gpt-ai-assistant-arguskao.vercel.app/webhook 也填寫了

但是機器人已讀不回...

https://lin.ee/oZorewX
這是我的機器人

**Comment by ys5603** [comment]
> https://gpt-ai-assistant-arguskao.vercel.app/
> 
> 我重新裝，https://gpt-ai-assistant-arguskao.vercel.app/webhook 也填寫了
> 
> 但是機器人已讀不回...
> 
> https://lin.ee/oZorewX 這是我的機器人

如果直接連到https://gpt-ai-assistant-arguskao.vercel.app 會出現ok，問題應該跟我一樣

**Comment by arguskao** [comment]
我終於成功了

**Comment by memochou1993** [comment]
@arguskao 

Thanks & Congrats!
