### ISSUE TITLE
回覆在 Line 裡面會被截掉不完整

### ISSUE THREAD

**Issue by VicKuo0516** [memochou1993/gpt-ai-assistant#160]
ChatGPT回覆在Line裡面會被截掉不完整, 請問是哪邊有問題?
<img width="1066" alt="截圖 2023-02-24 上午9 30 21" src="https://user-images.githubusercontent.com/48739965/221084052-36b7b700-8a35-4992-8f82-9b869cd6719c.png">

**Comment by memochou1993** [comment]
@VicKuo0516 

為了避免 AI 回覆長文，有限制他的字數，請用「繼續」回覆他。

你也可以使用手機版，會跳出「繼續」按鈕喔！
