### ISSUE TITLE
還沒開始使用就出現 429 Too Many Requests

### ISSUE THREAD

**Issue by chowder77** [memochou1993/gpt-ai-assistant#161]
我剛設定好所有流程後，就出現系統回覆以下，該如何解決?
Request failed with status code 429
POST https://api.openai.com/v1/completions
You exceeded your current quota, please check your plan and billing details.

**Comment by chowder77** [comment]
補充，open AI是還有額度的，完全沒有使用過
![image](https://user-images.githubusercontent.com/126219954/221093702-49cc88a5-eba6-4c5a-8a78-21e7d389bd67.png)

**Comment by clspeter** [comment]
這應該是沒額度，可以用的額度是顯示$x.xx / $18.00

**Comment by memochou1993** [comment]
@chowder77 

請確認一下，你註冊的這個帳號，手機號碼有重複使用過嗎？

**Comment by AllimonttiHome** [comment]
謝謝 遇到相同問題
手機號碼重複申請OPENAI帳號是可以的 但是
看起來只有第一個申請的帳號有額度可以使用

> @chowder77
> 
> 請確認一下，你註冊的這個帳號，手機號碼有重複使用過嗎？

**Comment by memochou1993** [comment]
一個手機號碼只有一個額度如果你要第二個帳號也可以使用，要用第二個手機號碼喔！Memo Chou 從 iPhone 傳送AllimonttiHome ***@***.***> 於 2023年2月27日 15:00 寫道：﻿
謝謝 遇到相同問題
手機號碼重複申請OPENAI帳號是可以的 但是
看起來只有第一個申請的帳號有額度可以使用

@chowder77
請確認一下，你註冊的這個帳號，手機號碼有重複使用過嗎？

**Comment by ericchen930150** [comment]
請問可以取消第一個申請的帳號，然後使用第二個帳號來使用額度嗎?
因為第一個申請的帳號是公司的帳號....

**Comment by memochou1993** [comment]
@ericchen930150 

你用公司帳號綁自己的手機號碼嗎⋯⋯？

**Comment by ericchen930150** [comment]
對，
我第一次自己註冊openai時，是用公司的帳號綁自己的手機號碼，
抱歉。

**Comment by memochou1993** [comment]
寫信給 OpenAI 吧😂

**Comment by ericchen930150** [comment]
好，謝謝您的建議~
