### ISSUE TITLE
關閉自動回覆後還需要設定 BOT_NAME 才會生效

### ISSUE THREAD

**Issue by clspeter** [memochou1993/gpt-ai-assistant#162]
拿掉預設值`BOT_NAME:AI`之後即使關閉自動回覆還是每句回覆，需要設定BOT_NAME才生效，但說明文件裡未修改還是標示有預設值

**Comment by memochou1993** [comment]
@clspeter 

有 bug 喔！感謝提醒！

**Comment by memochou1993** [comment]
好厲害，有發現 `BOT_NAME` 預設值不見了，已在 v3.4.1 修正！
