### ISSUE TITLE
已讀無回。最新設定 2023-02-26

### ISSUE THREAD

**Issue by move9102** [memochou1993/gpt-ai-assistant#166]

**Comment by memochou1993** [comment]
@move9102

請提供在哪個步驟遇到問題和截圖，才能協助你找到問題。

**Comment by move9102** [comment]
![_20230226_112224.JPG](https://user-images.githubusercontent.com/126368474/221413050-d2401a0e-8d83-4ed7-a020-d064bd7de9e7.JPG)

**Comment by memochou1993** [comment]
環境變數都填妥了嗎？

在 LINE 按 Verify 有成功？

**Comment by move9102** [comment]
好的，我再仔細地確認一次再回覆你。
