### ISSUE TITLE
請問 GPT 的版本能否更新？

### ISSUE THREAD

**Issue by ys5603** [memochou1993/gpt-ai-assistant#17]
您好：
我完成架構後發現資料庫只有到2020/5/19，版本也是2.4的，請問該怎麼做才能更新資料庫與版本？謝謝

**Comment by memochou1993** [comment]
@ys5603 

嗨。

目前 OpenAI 開放的 API 是基於 [GPT-3](https://beta.openai.com/docs/models/gpt-3) 模型集合。

而 `gpt-ai-assistant` 預設採用的是 GPT-3 的 `text-davinci-003` 模型，資料到 2021 年 6 月。

目前還無法透過官方手段更新到 GPT-3.5 喔！

**Comment by ys5603** [comment]
> @ys5603
> 
> 嗨。
> 
> 目前 OpenAI 開放的 API 是基於 [GPT-3](https://beta.openai.com/docs/models/gpt-3) 模型集合。
> 
> 而 `gpt-ai-assistant` 預設採用的是 GPT-3 的 `text-davinci-003` 模型，資料到 2021 年 6 月。
> 
> 目前還無法透過官方手段更新到 GPT-3.5 喔！

感謝回覆！
