### ISSUE TITLE
Request failed with status code 429

### ISSUE THREAD

**Issue by Alic54** [memochou1993/gpt-ai-assistant#171]
Request failed with status code 429
POST https://api.openai.com/v1/compietions

help

**Comment by memochou1993** [comment]
@Alic54 

Please check your OpenAI usage.

https://platform.openai.com/account/usage

<img width="864" alt="image" src="https://user-images.githubusercontent.com/38420282/221596583-029fe07b-3f72-46c1-b436-cb97a2e77157.png">
