### ISSUE TITLE
已完成安裝，但沒有回覆

### ISSUE THREAD

**Issue by pikashtw** [memochou1993/gpt-ai-assistant#173]
我在 LINE Developers 設定上已完成，Messaging API 底下的Verify 也測試成功，但是仍無法自動回覆我的問題，可否請版大協助告知可能錯誤的地方

**Comment by memochou1993** [comment]
請問是已讀不回還是不讀不回？

聊天內容有錯誤訊息嗎？

環境變數是否填妥？

請提供一些截圖，比較好除錯。

**Comment by kuometeor** [comment]
輸入:查詢日期 回復:缺少環境變數：SERPAPI_API_KEY ~~~請大神協助

**Comment by memochou1993** [comment]
你是只有查詢指令沒有回覆，還是任何訊息都沒有回覆？

**Comment by kuometeor** [comment]
它現在正常了，感謝大神從我的iPhone傳送Memo Chou ***@***.***> 於 2023年3月1日 13:08 寫道：﻿
你是只有查詢指令沒有回覆，還是任何訊息都沒有回覆？

**Comment by pikashtw** [comment]
版大: 我的情況是已讀不回， 不會有錯誤訊息
至於環境變數，我在試試重新測試看看。

**Comment by memochou1993** [comment]
@pikashtw 

參考[常見問題](https://memochou1993.github.io/gpt-ai-assistant-docs/questions.html#%E7%82%BA%E4%BB%80%E9%BA%BC-ai-%E4%B8%8D%E8%AE%80%E4%B8%8D%E5%9B%9E)，無法解決再提出來～
