### ISSUE TITLE
webhook 有問題該如何解決

### ISSUE THREAD

**Issue by janice880624** [memochou1993/gpt-ai-assistant#177]
![image](https://user-images.githubusercontent.com/47550853/222434014-8ad31f82-b0b9-4a09-8a64-2baed62d215e.png)

![image](https://user-images.githubusercontent.com/47550853/222433561-53eac907-b5ff-42fa-b1d9-8c3f27e410fa.png)

**Comment by memochou1993** [comment]
@janice880624 

可以幫我看有錯的那一條 log 打開來，錯誤訊息寫什麼嗎？

可以的話，貼上來好了，謝謝。

**Comment by janice880624** [comment]
![image](https://user-images.githubusercontent.com/47550853/222470652-c344d51b-dd77-435e-b447-7395ab3b853f.png)
![image](https://user-images.githubusercontent.com/47550853/222470687-d214e6be-7fb9-419a-844f-3ec258919656.png)
![image](https://user-images.githubusercontent.com/47550853/222470802-330e0e8c-a3ea-4463-9562-1aeb6532835a.png)

fail 那邊我確定 Channel access token 是正確得

**Comment by memochou1993** [comment]
可以幫我看一下你的 Vercel 的專案叫什麼嗎？

**Comment by janice880624** [comment]
futurenest-assisant

上次月我也有改過專案名稱也有架成功

**Comment by memochou1993** [comment]
試試這個 `VERCEL_PROJECT_NAME` 環境變數吧！

https://memochou1993.github.io/gpt-ai-assistant-docs/environments.html#一覽

**Comment by janice880624** [comment]
我後來重新佈署後 今天就成功了 xd
