### ISSUE TITLE
無法加入聊天群

### ISSUE THREAD

**Issue by yuan-tp** [memochou1993/gpt-ai-assistant#178]
已增加環境變數 APP_MAX_GROUPS 5 了
還是無法加入聊天群

**Comment by memochou1993** [comment]
@yuan-tp 

參考這篇：

https://memochou1993.github.io/gpt-ai-assistant-docs/questions.html#可以將-ai-加到群組中嗎

**Comment by yuan-tp** [comment]
> @yuan-tp
> 
> 參考這篇文章：
> 
> [https://memochou1993.github.io/gpt-ai-assistant-docs/questions.html#可以將-ai-加到群中嗎](https://memochou1993.github.io/gpt-ai-assistant-docs/questions.html#%E5%8F%AF%E4%BB%A5%E5%B0%87-ai-%E5%8A%A0%E5%88%B0%E7%BE%A4%E7%B5%84%E4%B8%AD%E5%97%8E)

有的
兩人聊天群可以加入沒問題
二十幾人和快滿員的聊天群無法加入
(滿員是500人)

![photo_2023-03-03_16-46-40](https://user-images.githubusercontent.com/126773535/222675099-b1361181-0702-4f16-9a24-8c2fdfeb1eb2.jpg)
![photo_2023-03-03_16-46-34](https://user-images.githubusercontent.com/126773535/222675108-ae32f3ad-6728-4ffc-be94-e1f5defa6856.jpg)
![photo_2023-03-03_16-46-22](https://user-images.githubusercontent.com/126773535/222675110-014b28a9-659c-45e6-b786-e75fac9c4fb4.jpg)

**Comment by memochou1993** [comment]
有什麼錯誤訊息嗎？

**Comment by yuan-tp** [comment]
> 有什麼錯誤信息嗎？

Line上就顯示
"XX已邀請XX加入群組,等對方加入再一起聊天吧!"
然後就沒有了

**Comment by yuan-tp** [comment]
搞定了
是沒設置 VERCEL_ACCESS_TOKEN

https://www.youtube.com/watch?v=77ggAZPy0mI

**Comment by memochou1993** [comment]
@yuan-tp 

原來有新影片，讚
