### ISSUE TITLE
目前串 GPT 的 LINE 機器人有機會變成人類可介入的客服機器人嗎？

### ISSUE THREAD

**Issue by keanuhsieh** [memochou1993/gpt-ai-assistant#179]
有在想如何做一個 平常用 fine-tuned GPT 回覆客人詢問產品訊息，但是關鍵步驟後可以用人工接手的 LINE 機器人。

當然前題是人類要能看得到 GPT 與客人的對話，也可以適時停止 GPT 繼續回覆。

**Comment by memochou1993** [comment]
@keanuhsieh 

目前已經可以透過 LINE 後台看到 GPT 和客人的對話，

也能透過關閉自動回覆暫時性關閉 GPT 回應，

透過角色塑造，也能夠將特定知識餵給 GPT，所以我認為是有機會變成客服機器人的。

**Comment by s6601** [comment]
> @keanuhsieh
> 
> 目前已經可以透過 LINE 後台看到 GPT 和客人的對話，
> 
> 也能透過關閉自動回覆暫時性關閉 GPT 回應，
> 
> 透過角色塑造，也能夠將特定知識餵給 GPT，所以我認為是有機會變成客服機器人的。

想請教看對話後台的方式

**Comment by memochou1993** [comment]
這邊可以看對話，請參考：

<img width="662" alt="image" src="https://user-images.githubusercontent.com/38420282/222915968-15a8e824-c5e0-4813-bfaa-fd67953e6149.png">

<img width="528" alt="image" src="https://user-images.githubusercontent.com/38420282/222915978-41840783-8d3b-4d15-a98f-821414cbadc8.png">

<img width="322" alt="image" src="https://user-images.githubusercontent.com/38420282/222915993-58d429c6-bb1c-4e7c-b89f-244b3be58258.png">

**Comment by s6601** [comment]
看到了 謝謝回覆

**Comment by keanuhsieh** [comment]
![image](https://user-images.githubusercontent.com/12395607/222936506-ae57a692-5b85-44ef-94c7-7f075e413e10.png)
那這裡要勾哪一個回應方式？才不會讓 WEBhook 回應失效？

**Comment by keanuhsieh** [comment]
> @keanuhsieh
> 
> 目前已經可以透過 LINE 後台看到 GPT 和客人的對話，
> 
> 也能透過關閉自動回覆暫時性關閉 GPT 回應，
> 
> 透過角色塑造，也能夠將特定知識餵給 GPT，所以我認為是有機會變成客服機器人的。

關閉自動回覆暫時性關閉 GPT 回應，具體指的是哪裡關掉？

**Comment by memochou1993** [comment]
@keanuhsieh 

勾第一個手動聊天即可。

對，要去後台看過聊天內容之後才會已讀，這是 LINE 現在的特性。

使用「關閉自動回覆」指令，可以讓 AI 不要自動回覆。

可以試試看。

**Comment by keanuhsieh** [comment]
目前試做，在機器人聊天室後台輸入「關閉自動回覆指令」
![image](https://user-images.githubusercontent.com/12395607/222945939-1f4307ae-7904-4fde-a5eb-b0edb0b0b364.png)

藍色底是 Webhook 回覆；綠色是人工回覆。
　
　
　
實際情況是，機器人不會「關閉自動回覆」，除非有對方端下指令。
![image](https://user-images.githubusercontent.com/12395607/222945913-8e36f379-2abe-436e-95a3-35cb1fed3620.png)
　
　
　
我推測是，在 Line 的 webhook 運作，是客戶端來的訊息才會丟出去。己方的訊息不會丟上 webhook 。
這樣也有道理，不然 webhook 會一直 echo 。

**Comment by memochou1993** [comment]
@keanuhsieh 

你測試的沒錯，我忘記了。

關閉自動回覆只會對發出訊息的人有效，這是程式當初這麼設計的，不然大家開關會互相影響。

目前還沒辦法做到關閉某個人的自動回覆，這會牽涉到權限問題，程式面也會需要做許多修改。

這個專案有它的局限性在，如果有商業考量，可以透過信箱聯繫我，討論相關需求。

感謝！
