### ISSUE TITLE
將程式部署到 Fly.io 平台

### ISSUE THREAD

**Issue by arguskao** [memochou1993/gpt-ai-assistant#18]
我想上傳到Fly.io 上，不知道那個環境變數能不能寫在程式裡面？！

**Comment by memochou1993** [comment]
@arguskao

你可以找一下 fly.io 哪裡可以填環境變數，像是 Secrets 頁籤。

或是你可以在 config 的地方，綁預設值改掉就好。

好奇問一下選 fly.io 的原因？超時時間比較久嗎？
