### ISSUE TITLE
問問題他都不回我

### ISSUE THREAD

**Issue by gordanchen** [memochou1993/gpt-ai-assistant#185]
![image](https://user-images.githubusercontent.com/126982681/222924675-0f1b3782-5be3-45eb-835b-dd9307e63c48.png)

**Comment by keanuhsieh** [comment]
![image](https://user-images.githubusercontent.com/12395607/222936895-15004d41-785d-48ef-ad3b-058a6d9f814d.png)
看你的錯誤訊息應該是 api key 出問題

看一下手冊的 「為什麼 AI 不讀不回？」「為什麼 AI 已讀不回？」
https://memochou1993.github.io/gpt-ai-assistant-docs/questions.html#%E7%82%BA%E4%BB%80%E9%BA%BC-ai-%E4%B8%8D%E8%AE%80%E4%B8%8D%E5%9B%9E

**Comment by memochou1993** [comment]
@gordanchen 

對，看起來應該是 LINE 的 `LINE_CHANNEL_ACCESS_TOKEN` 填錯了！

感謝 @keanuhsieh 幫忙回答！

**Comment by keanuhsieh** [comment]
我加碼回饋一下，這一波更新完，我把一些我看起來有需求的環境變數加上去後，出現已讀不回的情況。我陸續刪除和調整幾個變數後才恢復正常。

我刪除的變數與值如下：
HUMAN_NAME　　　　　　　''
HUMAN_INIT_PROMPT　　　''
BOT_INIT_PROMPT　　　　　''
BOT_TONE　　　　　　　　　''


我刪改的變數與值如下：
變數　　　　　　　　　原值　　　　　　　　　　　　修改後
APP_API_TIMEOUT　　　9000　　　　　　　　　　　　刪除
VERCEL_TIMEOUT　　　<APP_API_TIMEOUT>　　　　　9000
OPENAI_TIMEOUT　　　<APP_API_TIMEOUT>　　　　　9000
LINE_TIMEOUT　　　　　<APP_API_TIMEOUT>　　　　　9000
SERPAPI_TIMEOUT　　　<APP_API_TIMEOUT>　　　　　9000

**Comment by gordanchen** [comment]
跟女友一樣....有脾氣
愛已讀不回

**Comment by gordanchen** [comment]
![image](https://user-images.githubusercontent.com/126982681/222962620-f170a787-5a10-439f-bef2-61e6cb545f0e.png)
ㄇ每個都改了還是錯誤

**Comment by memochou1993** [comment]
@gordanchen 

確認環境變數真的沒錯嗎！？
