### ISSUE TITLE
更新後，直接發問會已讀不回

### ISSUE THREAD

**Issue by leader596** [memochou1993/gpt-ai-assistant#187]
您好!今天更新版本後,不知為何回答變得很慢?有時已讀不回,發問時若沒先打招呼喚醒它,直接發問也會已讀不回,還請協助釋疑.感謝~

**Comment by memochou1993** [comment]
確認一下，你用「指令」送出，看一下現在自動回覆的狀態是開啟的還是關閉的？

**Comment by leader596** [comment]
會出現這個
![image](https://user-images.githubusercontent.com/125934917/222940048-62ac1cfd-ff1b-4812-8783-c9fd9c74ee37.png)

**Comment by leader596** [comment]
發問後無反應
這個給您參考
![image](https://user-images.githubusercontent.com/125934917/222940978-d3a8fb5c-cfa4-417e-90b4-1ab78326e480.png)

**Comment by leader596** [comment]
> 確認一下，你用「指令」送出，看一下現在自動回覆的狀態是開啟的還是關閉的？
會出現這個
![image](https://user-images.githubusercontent.com/125934917/222941082-0bd33685-13ed-4b20-82ed-818490b8a57f.png)
發問後無反應
這個給您參考
![image](https://user-images.githubusercontent.com/125934917/222941092-fe693c86-cd1f-40b8-a774-bfb808746784.png)

**Comment by memochou1993** [comment]
@leader596 

錯誤代碼 504，有可能是超時了，處理時間太久！
