### ISSUE TITLE
更新後查看版本還是舊版的？

### ISSUE THREAD

**Issue by Terence0816** [memochou1993/gpt-ai-assistant#189]
請問 vercel.com 我裡面也顯示4.0.4  ，但在LINE 查詢版本還是 3.0.0

vercel.com 裡面也有重新部署了，也顯示 4.0.4，但是 LINE 那邊詢問版本還是 3.0.0

想問下是什麼原因呢？要怎麼修正？

另外 vercel.com  我之前有部署過 2 - 3 個
因為之前第一個部署 LINE 都不會回覆，所以又有創新的

但昨天已經把其他部署都刪掉了，只留目前使用的這一個
但一樣重新部署後，回LINE 檢測版本還是舊的

想問有沒有辦法處理呢

**Comment by Terence0816** [comment]
已解決了

webhook 要設定在 DOMAINS 的網址
設在 DEPLOYMENT 那邊可用，但更新不會跟著更新

謝謝~

**Comment by memochou1993** [comment]
OK
