### ISSUE TITLE
更新後頻繁出現錯誤代碼 504

### ISSUE THREAD

**Issue by leader596** [memochou1993/gpt-ai-assistant#190]
嗨~更新後頻繁出現錯誤代碼 504，請教是否哪邊可修正?

**Comment by memochou1993** [comment]
請問是文字訊息還是語音訊息？

是很長的問題嗎？

**Comment by leader596** [comment]
您好
一般有以下狀況：
1：直接發問時都未回應
2：跟他打個招呼後，再丟問題，他會回應，再來就是對話過程中若有間隔較長時，他也會停止回應，變成要先跟他打再個招呼，他才會又開始回應，但就變成無法接續剛剛的話題。
舉例如下，都是簡單的問題，不長。請參考，感謝您



Memo Chou ***@***.***> 於 2023年3月5日 週日 下午3:13 寫道：

**Comment by memochou1993** [comment]
如果常常未回應，可能就是 OpenAI 那邊速度太慢了

只能使用 Vercel 付費版解決這個問題。

**Comment by eric816318** [comment]
我遇到相同的問題
長一點的回覆都會504

**Comment by chnejohnson** [comment]
遇到同樣的問題...我認為這個 issue 應該保持開啟
