### ISSUE TITLE
如何設定Bot回覆語氣?

### ISSUE THREAD

**Issue by ekids9702122935** [memochou1993/gpt-ai-assistant#194]
你好，請問如何設定AI的回覆語氣? 有看到BOT_TONE的參數，不過不清楚這邊要填寫什麼，如果想要以嘲諷的語氣回覆，填寫"嘲諷"會不會跟指令有衝突? 或是再請您舉個設定的例子，謝謝分享~

**Comment by memochou1993** [comment]
環境變數 `BOT_TONE` 寫嘲諷兩個字就好
