### ISSUE TITLE
支援 Vercel  Pro 方案

### ISSUE THREAD

**Issue by eric816318** [memochou1993/gpt-ai-assistant#195]
把vercel的project更新到pro版後
log變500
line上的Webhook URL 有改成新的
Request failed with status code 404
GET https://api.vercel.com/v9/projects/gpt-ai-assistant/env
{ error: { code: 'NOT_FOUND' } }
這是什麼原因呢

確認過該project內的setting 環境變數設置都還在

**Comment by memochou1993** [comment]
@eric816318 

確認在 Vercel 的專案名稱和 GitHub 的一樣嗎？

**Comment by eric816318** [comment]
是的 一樣
<img width="298" alt="圖片" src="https://user-images.githubusercontent.com/126769566/223023165-0a8a9330-2073-42a5-b922-2c0a0224b03f.png">

**Comment by memochou1993** [comment]
可以把錯誤訊息貼上來嗎

**Comment by eric816318** [comment]
只有那一串
我重建一個project好了
只是移到pro版team裡面的那個就不能用
本來是想說用Vercel pro看能否解決超時的問題
（有時問問題會已讀不回）

**Comment by memochou1993** [comment]
我有認識已經有人升到 Pro 後，完全解決超時的問題。

麻煩試試看了～希望可以成功。

**Comment by eric816318** [comment]
更新
VERCEL_ACCESS_TOKEN
我把pro裡面專案中的這個環境變數拿掉後正常了
不知道為什麼同一個project裡的VERCEL_ACCESS_TOKEN 移到pro裡的team會失敗

**Comment by memochou1993** [comment]
照理說 `VERCEL_ACCESS_TOKEN` 應該沒有區分環境才對 🤔 

重新產生一個 token 看看呢，畢竟這個環境變數還是需要的。

**Comment by eric816318** [comment]
<img width="276" alt="圖片" src="https://user-images.githubusercontent.com/126769566/223075370-7376df75-d81d-4e74-8456-76fa608b1d97.png">
看來個人與企業team的token不同用

**Comment by eric816318** [comment]
Request failed with status code 403
GET https://api.vercel.com/v9/projects/gpt-ai-assistant/env
{
  error: {
    code: 'forbidden',
    message: 'Not authorized: Trying to access resource under scope "eric816318". You must re-authenticate to this scope or use a token with access to this scope.',
    saml: true,
    teamId: null,
    scope: 'eric816318',
    enforced: false
  }
}

加入VERCEL_ACCESS_TOKEN 又壞了
status 500

**Comment by eric816318** [comment]
我看下是什麼存取權限

**Comment by memochou1993** [comment]
是 `scope` 的問題嗎？

**Comment by eric816318** [comment]
應該是 但我還沒找到scope的權限怎麼設定

**Comment by memochou1993** [comment]
新建 token 的時候，選你的 team 這樣？

<img width="947" alt="截圖 2023-03-06 下午6 01 45" src="https://user-images.githubusercontent.com/38420282/223078593-16cd8490-be21-4d16-9af7-0dd356faab86.png">

**Comment by eric816318** [comment]
是 我剛剛重建一個的時候 選了team的這個 
產出的仍不行

**Comment by memochou1993** [comment]
我印象中，專案好像要 import 進去這個 team 裡面，好像需要做這個動作。

**Comment by eric816318** [comment]
<img width="259" alt="圖片" src="https://user-images.githubusercontent.com/126769566/223079127-e2afbec4-d7b1-4e7d-9f02-a6bd58303ea2.png">
這個是剛剛建立的團隊的token仍不行

專案好像要 import 進去這個 team 裡面
這個在升級成pro的時候 就有做

**Comment by eric816318** [comment]
我用Vercel CLI  試試看

**Comment by coastk05396** [comment]
https://vercel.com/guides/how-do-i-use-a-vercel-api-access-token

pro 版的 好像要多宣告一個teamId  跟 personal 的不太一樣 !?

const teamId = 'replace-me'     //need to append ?teamId=<your-team-id> to the URL
const result = await fetch(
    `https://api.vercel.com/v6/deployments?teamId=${teamId}`,
    {
        method: 'GET',
        headers: {
            Authorization: `Bearer ${process.env.VERCEL_ACCESS_TOKEN}`,
        }
    }
);

**Comment by memochou1993** [comment]
@thuangfpc 

那請問重新新增一個專案是有用的嗎？

你目前在 Pro 版開啟自動回覆、關閉自動回覆是有效的狀態嗎？

**Comment by eric816318** [comment]
@memochou1993  我是免費14天 
確實有解決504問題

**Comment by memochou1993** [comment]
@eric816318

有成功了嗎？

所以你知道 token 的問題是怎樣嗎？

**Comment by memochou1993** [comment]
請各位等一下，需要請 @mics8128 幫忙驗證一下改動，感謝～

**Comment by mics8128** [comment]
合併後目前使用上沒有問題 👍👍👍

**Comment by memochou1993** [comment]
感謝 @mics8128 的貢獻，已合併至主專案。

請使用 Pro 版的大家更新到  `v4.3.0` 版，並新增 `VERCEL_TEAM_ID ` 試試效果。

<img width="752" alt="image" src="https://user-images.githubusercontent.com/38420282/223616700-944da5d2-ef4e-422c-93a5-665f5f89ab6e.png">

![image](https://user-images.githubusercontent.com/38420282/223616908-2860aabe-f613-4bae-9674-cc8b29877595.png)

**Comment by coastk05396** [comment]
最近  變超級慢 很有感....

跟各位分享一個PRO方案 超時14天後的方法:

1. 同個帳號再去創第二個team(就會再有14天)
2. 去第一個TEAM 點擊裡面的 **Transfer project** 直接clone project到第二個TEAM
3.  記得新增**VERCEL_TEAM_ID** 跟 **VERCEL_ACCESS_TOKEN** 的變數 並Redeploy(不同的TEAM  這兩個環境變數不一樣)
4. 這樣你的PRO Trail 又會有14天囉~

**Comment by memochou1993** [comment]
請各位試試看，有問題再提出，感謝～
