### ISSUE TITLE
無法關閉自動回覆

### ISSUE THREAD

**Issue by sky770825** [memochou1993/gpt-ai-assistant#198]
己經將BOT_DEACTIVATED環境變數設置為true跟F都設定過，還是會自動回覆訊息。
BOT_NAME設定為#

重新部屬後回話依然不加#還是會回覆><
大神能否幫忙測試一下呢？
感謝幫忙

**Comment by memochou1993** [comment]
可以給個截圖嗎？

有沒有用「自動關閉回覆」先關掉呢？

**Comment by sky770825** [comment]
感謝己經可以了~

**Comment by memochou1993** [comment]
OK
