### ISSUE TITLE
想詢問 AI 回覆訊息後選單

### ISSUE THREAD

**Issue by sky770825** [memochou1993/gpt-ai-assistant#199]
會出現『繼續』這個選單
請問這個部份有辦法自行做新增嗎？

感謝~

**Comment by memochou1993** [comment]
目前是否出現「繼續」，是去判斷 AI 講完話了沒；還沒講完的話，就會出現。

不曉得你的使用情境是怎樣？

**Comment by sky770825** [comment]
對的，我的意思是，選單可否新增。目前是對話還沒說完，他會寫繼續。那麼如果有業務上的需求，會再繼續的旁邊再置入一個 飲料菜單，點擊選單，出現文字。除了原本問的問答之外的額外複選項，用在個人商業IP上的便捷^^"

**Comment by memochou1993** [comment]
商業平台目前有在規劃，可以納入考量。

對現在這個小型的實驗專案可能太吃力了。

感謝回饋。
