### ISSUE TITLE
客製化按鈕

### ISSUE THREAD

**Issue by sean284150** [memochou1993/gpt-ai-assistant#203]
![09A217D6-74F0-46F1-B563-1F74B41B592A](https://user-images.githubusercontent.com/126972640/223412367-7fdddb2f-1663-4240-b26b-2b75b9dfbde0.jpeg)

如圖，我想做幾個按鈕放上去，用戶點擊時可以自動傳送訊息，讓AI充當翻譯官等等

**Comment by memochou1993** [comment]
@sean284150 

目前沒有客製化按鈕的功能耶

目前有「翻成英文」和「翻成中文」的指令，還是把這兩個按鈕做上去如何？

**Comment by sean284150** [comment]
可以阿

**Comment by memochou1993** [comment]
@sean284150 

我可以加上客製化按鈕的功能，不過情境會變成這樣

```
User: 你好嗎？
AI: 我很好。
User: 上一句翻成英文
AI: How are you?
```

變成 AI 會先回話給你，這樣你覺得會奇怪嗎？

**Comment by memochou1993** [comment]
先關閉，有需要再提出。
