### ISSUE TITLE
修改環境變數後，新的部署有 Webhook 的問題

### ISSUE THREAD

**Issue by jimmy8399** [memochou1993/gpt-ai-assistant#208]
在修改前的都不會發生無法串接到line後台，一改之後所產生的新部屬就無法被line串接 會出現500錯誤

**Comment by memochou1993** [comment]
改了哪些環境變數？

可以貼上來一些截圖嗎？

**Comment by jimmy8399** [comment]
![image](https://user-images.githubusercontent.com/126844891/223599818-ab552cd5-4a4f-4b3a-9391-ede2e6605201.png)
改前
![image](https://user-images.githubusercontent.com/126844891/223600177-e7c49d16-5878-4dc4-8019-fddea83e7fcf.png)
修改內容

修改後line後臺都會變成500
![image](https://user-images.githubusercontent.com/126844891/223600670-68befe67-b477-4b6b-8b83-3f7866b547d3.png)

**Comment by memochou1993** [comment]
要不要試試看全部刪掉，再設置一次呢？

**Comment by jimmy8399** [comment]
有的 試過幾次都是跳500
https://www.youtube.com/watch?v=77ggAZPy0mI
照著這個步驟去操作的 不確定vercel端是否有做更新

**Comment by memochou1993** [comment]
那請問你的 GitHub 專案名稱和 Vercel 專案名稱一樣嗎？

**Comment by jimmy8399** [comment]
![image](https://user-images.githubusercontent.com/126844891/223612875-4a2bb8c9-6c5c-48bb-a9f5-f4de1340b04d.png)
這這是我目前的專案 是跟git名稱一樣的

**Comment by memochou1993** [comment]
那貼一下你的應用程式的網址

**Comment by memochou1993** [comment]
幫我進到這裡看錯誤訊息是什麼？

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/38420282/223617659-3ca4d3f9-7b21-44d5-ab84-60d9f8264293.png">

**Comment by jimmy8399** [comment]
![image](https://user-images.githubusercontent.com/126844891/223618220-47f5e335-b26f-4ad0-9b7f-f535a615ce4a.png)
沒記錯是這兩個紅的時間

**Comment by jimmy8399** [comment]
![image](https://user-images.githubusercontent.com/126844891/223618323-9dbcf956-348f-4820-9878-26792ec316c2.png)
這個是剛才更新成4.3.0 但是line後台目前正常驗證 對話上如果不算超時以外都沒問題
![image](https://user-images.githubusercontent.com/126844891/223618457-0fbadaf6-8266-4b44-b46c-b44a5e01feb0.png)

**Comment by memochou1993** [comment]
感覺這樣就正常了，對吧？

至於，超時問題就是另一張票了⋯⋯

**Comment by jimmy8399** [comment]
我還沒試修改變數 因為下圖是我又重新開了一個專案來做的 
![image](https://user-images.githubusercontent.com/126844891/223619096-fb58a36d-15db-4b39-8a21-7e7c37be33ea.png)

**Comment by memochou1993** [comment]
那可以試試看修改變數，因為不太可能因為修改變數就驗證失敗耶。

**Comment by jimmy8399** [comment]
修好了 謝謝老師

**Comment by jimmy8399** [comment]
![image](https://user-images.githubusercontent.com/126844891/223620088-49f3a4bc-28aa-4fa1-a36b-8d36346a78db.png)
這個後就正常了

**Comment by memochou1993** [comment]
不過你是 Pro 方案還是免費方案呀！？

**Comment by jimmy8399** [comment]
![image](https://user-images.githubusercontent.com/126844891/223620316-e0e6f9c4-1c7d-4353-8135-207296bd9ba5.png)
他有給免費的用量

**Comment by memochou1993** [comment]
哦，我是說 Vercel 的部分

**Comment by jimmy8399** [comment]
vercel是免費的

**Comment by memochou1993** [comment]
哦，那就和 Team 沒關係。

可能是別的影響，有遇到問題再提出來看看吧！
