### ISSUE TITLE
機器人沒有回應，Vercel Log 如圖。

### ISSUE THREAD

**Issue by imfranktw** [memochou1993/gpt-ai-assistant#210]
機器人沒有回應，Vercel Log 如圖。
![Vercel log 畫面 2023-03-08 150824](https://user-images.githubusercontent.com/98247289/223644264-a85a92ed-ffe7-4bc6-94b3-bfe41126de8f.jpg)

**Comment by memochou1993** [comment]
@imfranktw 

混入空格之類的，重填一次看看。

https://memochou1993.github.io/gpt-ai-assistant-docs/questions.html#為什麼-line-訊息中出現-invalid-character-錯誤

**Comment by 0524tim** [comment]
![螢幕擷取畫面 2023-04-21 221958](https://user-images.githubusercontent.com/126672133/233660931-1db01ae0-74b2-4de9-8ad8-23caf7ed3461.png)
不好意思大神
我已經確認過多次都沒有空格，也換過新的API_KEY了。我想是不是照片裡的Merge branch'staging'的問題
