### ISSUE TITLE
支援 gpt-3.5-turbo-0301 語言模型

### ISSUE THREAD

**Issue by al2698** [memochou1993/gpt-ai-assistant#211]
我嘗試在 env 改為使用 gpt-3.5-turbo-0301，會出現 404。但預設就沒有這個問題，有人知道為甚麼？
[line_bot_error1](https://drive.google.com/file/d/18VfbSfFc8YXndE9HDMmLB34PmHv6tSPc/view?usp=sharing)

**Comment by memochou1993** [comment]
程式尚不支援，這個模型需要再加上！

**Comment by memochou1993** [comment]
@al2698 

支援了，請更新到 `4.4.0` 版本！
