### ISSUE TITLE
無法更新

### ISSUE THREAD

**Issue by timestoprun** [memochou1993/gpt-ai-assistant#212]
大大安安

已經有點選update了
出現以下畫面
![image](https://user-images.githubusercontent.com/8746630/223968993-a97295be-4eb2-464c-bed8-e76355e7b4c0.png)

但還是顯示目前版本4.2.2
![image](https://user-images.githubusercontent.com/8746630/223969088-b480afce-b8fb-4a7d-85de-14e355df6df5.png)
是哪裡沒有做到呢?

另外
我不是顯示4.4.0，顯示如下
![image](https://user-images.githubusercontent.com/8746630/223970724-44e45949-8c49-424b-a8ef-6506e4258187.png)

**Comment by memochou1993** [comment]
@timestoprun 

嗨，點一下 Deployments 後，看一下 Current 標籤的 Deployment 是哪一個？

截圖一下，謝謝。

**Comment by timestoprun** [comment]
> @timestoprun
> 
> 嗨，到 Vercel 點一下 Deployments 後，看一下 Current 標籤的 Deployment 是哪一個？
> 
> 截圖一下，謝謝。

Current標籤的Deployment 在哪裡...

**Comment by memochou1993** [comment]
真奇怪🤔

你的 URL 可以貼上來看一下嗎？

**Comment by timestoprun** [comment]
> 真奇怪🤔
> 
> 你的 URL 可以貼上來看一下嗎？

DEPLOYMENT
[gpt-ai-assistant-ah17dmfe3-timestoprun.vercel.app](https://vercel.com/timestoprun/gpt-ai-assistant/JBQD8GyiU8JnCPwtCxnm6kcRHcKJ)
DOMAINS
[gpt-ai-assistant-five-omega-72.vercel.app](https://gpt-ai-assistant-five-omega-72.vercel.app/)
+

**Comment by memochou1993** [comment]
從這點來看，程式沒有被重新部署。

https://gpt-ai-assistant-five-omega-72.vercel.app/info

看來 Vercel 機器人壞了。

只能把這個專案刪除，重新 import 一次了。
