### ISSUE TITLE
使用 Vercel Edge Function 架構

### ISSUE THREAD

**Issue by meerkat0688** [memochou1993/gpt-ai-assistant#214]
搜了一下好像用 edge function 可以解掉超時504 問題，也不用升級 vercel pro ，但不是寫code的人，有請高手看一下URL. thanks
https://vercel.com/blog/gpt-3-app-next-js-vercel-edge-functions#edge-functions-vs.-serverless-functions

**Comment by memochou1993** [comment]
感謝分享。

這篇不錯，可以研究一下。

**Comment by memochou1993** [comment]
看了一下，似乎一定要用 stream 的方式，這在網頁版也許可以，但在 LINE 的情境下可能不適用。

還是感謝提供參考！
