### ISSUE TITLE
LINE 平台點 Verify 失敗

### ISSUE THREAD

**Issue by kadamooshing** [memochou1993/gpt-ai-assistant#224]
我在創建時，  在Vercel平台 驗證呼叫成功有成功畫面，但是在Line上面點Verify就失敗了，不知道問題出在哪兒，是否能協助解決，希望能得到回應，感謝
![1678636150270](https://user-images.githubusercontent.com/127630461/224729387-a5703b23-d5ce-4532-9d4c-4cd77f02f67b.jpg)
![1678636204384](https://user-images.githubusercontent.com/127630461/224729454-de31c892-0143-4799-9a68-5a3f7e768e64.jpg)

**Comment by skywalker0823** [comment]
檢查一下Line 的 channel Secret 是否有被正確設定

**Comment by kadamooshing** [comment]
請教LINE_CHANNEL_SECRET這個名稱的大小寫有差別嗎?
我查看值是一樣的，但我名稱是小寫

**Comment by memochou1993** [comment]
當然有差啊

**Comment by kadamooshing** [comment]
更改成大寫一樣失敗了

**Comment by kkpan11** [comment]
@kadamooshing 我是遇到KEY改名的問題 (https://github.com/memochou1993/gpt-ai-assistant/commit/188c696f1b65302f0b02001ac9e82d37cf4bcd59)
改完新的KEY名redeply重試也無效，
後來發現應該是vercel deploy有cache機制，
redeploy不要勾選使用cache就成功了。

![Screen_Shot_2023-03-22_at_7_45_41_PM](https://user-images.githubusercontent.com/3894279/226899871-e842d35b-7d70-4161-b469-c7323cb187cf.png)
![Screen Shot 2023-03-22 at 7 46 04 PM](https://user-images.githubusercontent.com/3894279/226899940-397e93bb-18f6-4804-89cb-c5d2ced18aad.png)

**Comment by kadamooshing** [comment]
@kkpan11 測試成功了，謝謝你
