### ISSUE TITLE
LINE 訊息回覆限制

### ISSUE THREAD

**Issue by sky770825** [memochou1993/gpt-ai-assistant#226]
記得之前可以回覆很完整的一篇文，但現在只能大約10行或12行就要按繼續了，請問怎麼突破行數呢？

**Comment by meerkat0688** [comment]
調整OPENAI_COMPLETION_MAX_TOKENS參數

**Comment by sky770825** [comment]
調整有數值嗎？感覺他要回很長篇的話就直接沒回應了，短短的才會回，暈@@"

**Comment by sky770825** [comment]
我請他給我10個靈感，都無任何回應，設定160的話，約12行，也是要持續按繼續才會出來，受限，怎麼突破呢@@?感謝大大

**Comment by ChengDaWu** [comment]
我調整過OPENAI_COMPLETION_MAX_TOKENS參數，直接已不回，調回來後才正常

**Comment by sky770825** [comment]
嗯，我也是出現己讀不回，調回來一樣限制字數

**Comment by wobuxianggongzuo** [comment]
今天也遇到一樣的問題，一直要跟他說繼續有點麻煩
這邊提供一下我的解決方式：`OPENAI_COMPLETION_MAX_TOKENS 設定 2048 即可`

下面是參數修改過程
我先把 OPENAI_COMPLETION_MAX_TOKENS 調整成 4096，會出現以下錯誤訊息
`This model's maximum context length is 4097 tokens. However, you requested 4156 tokens (60 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.
`
看起來應該是我發送的訊息也算入 token 裡面，所以我把值改成一半 2048 就可以了。測試寫一篇 300 字作文是 OK 的！！

**Comment by sky770825** [comment]
我改成2048一樣不行…

**Comment by sky770825** [comment]
改成512也不行…都被己讀不回
