### ISSUE TITLE
群組與關閉自動回覆

### ISSUE THREAD

**Issue by ChengDaWu** [memochou1993/gpt-ai-assistant#228]
line bot加入群組後，為了避免它每一句都回，所以關閉了自動回覆，要叫他的名字他才會回應。
但回過頭來，一對一的對話也變成每一句都要叫他的名字 .......
似乎要建兩個bot才能解決問題.....

**Comment by tsu299** [comment]
> line bot加入群組後，為了避免它每一句都回，所以關閉了自動回覆，要叫他的名字他才會回應。 但回過頭來，一對一的對話也變成每一句都要叫他的名字 ....... 似乎要建兩個bot才能解決問題.....

我同一支BOT，群組上的關閉自動回覆後，一對一視窗是正常狀態，你要不要重啟AI然後再試試看?

**Comment by memochou1993** [comment]
群組的行為，並不會影響一對一的行為，請再確認喔。
