### ISSUE TITLE
群組的行為，並不會影響一對一的行為，請再確認喔。

### ISSUE THREAD

**Issue by ChengDaWu** [memochou1993/gpt-ai-assistant#229]
群組的行為，並不會影響一對一的行為，請再確認喔。

_Originally posted by @memochou1993 in https://github.com/memochou1993/gpt-ai-assistant/issues/228#issuecomment-1471916731_

**Comment by ChengDaWu** [comment]
抱歉，請問一下，自動回覆的關閉有分群組或一對一嗎？
因為我重啟後，一對一時仍要叫他的名字才會有回應耶......

**Comment by ChengDaWu** [comment]
好了，我又摸到了。我在一對一的對話中，叫他"開啟自動回覆",  這樣居然就可以了，版主的程式太神了

**Comment by memochou1993** [comment]
是有區分的！不然會被影響！
