### ISSUE TITLE
支援 GPT-4 語言模型

### ISSUE THREAD

**Issue by g0930270892** [memochou1993/gpt-ai-assistant#230]
目前版本是否可支援GPT-4的model?

**Comment by memochou1993** [comment]
先加入等候名單：

https://openai.com/waitlist/gpt-4-api

**Comment by g0930270892** [comment]
我已經收到邀請，我試著直接改版本別但會出現
This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?

**Comment by memochou1993** [comment]
因為 API 還沒出來，程式自然不支援
