### ISSUE TITLE
關於 Linode + Caddy 的方式部署

### ISSUE THREAD

**Issue by pvt5r486** [memochou1993/gpt-ai-assistant#233]
https://github.com/memochou1993/gpt-ai-assistant/issues/202#issuecomment-1461668667

有意想仿照作者以 Linode + Caddy 的方式部署，
但不確定如果改用這樣的方式，
那麼 VERCEL 的環境變數那些設定該怎麼處理呢?
或者是需要再另外改寫成 Linode 用的環境變數?

若您方便的話，不曉得是否能提供配置方式讓我做參考呢?
或者是作為補充能寫在文件上，讓願意走付費路線的朋友們有個指引 (看看那個 504...)
謝謝抽空回覆。

**Comment by memochou1993** [comment]
其實就是[文件](https://memochou1993.github.io/gpt-ai-assistant-docs/deployment.html#%E4%BD%BF%E7%94%A8-docker-%E5%AE%B9%E5%99%A8)寫的那樣，沒有什麼需要特別修改的地方。

只要用 Docker 啟動起來就好了。

```
APP_DEBUG=true
APP_URL=
APP_PORT=8000
APP_LANG=
APP_WEBHOOK_PATH=
APP_MAX_GROUPS=1
APP_MAX_USERS=100

HUMAN_NAME=主人
HUMAN_INIT_PROMPT=請你扮演一隻柴犬

BOT_NAME=柴柴
BOT_INIT_PROMPT=我知道了

VERCEL_TIMEOUT=60000
VERCEL_PROJECT_NAME=gpt-ai-assistant
VERCEL_ACCESS_TOKEN=
VERCEL_DEPLOY_HOOK_URL=

OPENAI_TIMEOUT=60000
OPENAI_API_KEY=必填
OPENAI_COMPLETION_MODEL=
OPENAI_COMPLETION_TEMPERATURE=1
OPENAI_COMPLETION_MAX_TOKENS=
OPENAI_COMPLETION_FREQUENCY_PENALTY=
OPENAI_COMPLETION_PRESENCE_PENALTY=
OPENAI_IMAGE_GENERATION_SIZE=

LINE_TIMEOUT=60000
LINE_CHANNEL_ACCESS_TOKEN=必填
LINE_CHANNEL_SECRET=必填

SERPAPI_TIMEOUT=60000
SERPAPI_API_KEY=選填
```

**Comment by pvt5r486** [comment]
我了解了， `VERCEL_ `開頭的環境變數可以保持空白沒關係對嗎?
(是說換成 linode 是不是就沒辦法設定 VERCEL_ACCESS_TOKEN 換句話說沒辦法用對話的方式開啟或關閉自動回覆了?)
也想參考 Caddy  的配置~
謝謝大大

**Comment by memochou1993** [comment]
@pvt5r486 

用 VPS 部署之後，有關 Vercel 的相關環境變數就都不再需要了。

當初為什麼會需要 Vercel 相關環境變數，是因為 Vercel 在一段時間後，記憶體狀態會重置。而這個專案為了不讓使用者另外串接資料庫，所以使出奇招，拿 Vercel 的環境變數當作持久化儲存空間的解決方案。

如果使用 VPS 的話，只要 Docker 容器不要重啟，記憶體狀態是不會重置的，因此開啟和關閉自動回覆的功能還是可以使用。

至於 Caddy 的配置可以參考以下：

**Comment by pvt5r486** [comment]
不好意思， @memochou1993 大大，
我再配置的時候出了一點問題，是不是能請你幫我看看呢?

我目前的環境是在 `linode` 上開了一台 `ubuntu 18.04` 的 VPS，
然後也安裝完 `docker` +` docker-compose` + `caddy`，
並在 goDaddy 上買了一個屬於自己的網域 `pvt5r486.xyz`
也配置好在 `linode` 上的 DNS 代管服務了

目前遇到的問題是， line 機器人會以讀不回的狀況，

我有成功運行 Caddy 以及 container ，並且在瀏覽器上輸入
`https://pvt5r486.xyz/` 有看到我設定好的文字。

並且在 line developers 上
`Webhook URL` 的欄位設定
`https://pvt5r486.xyz/gpt-ai-assistant/webhook` 
有驗證成功 (不過我後來發現如果只有 `https://pvt5r486.xyz/webhook`  也會跳成功...)

想請教作者，我是不是哪裡配置錯誤了，或者我疏忽了什麼?

以下是我的 `Caddyfile `以及 `.env `配置檔
---

Caddyfile
```
pvt5r486.xyz
{
        respond "Caddy is Running!"
        reverse_proxy 127.0.0.1:8000

        log {
                output file /var/log/caddy/gpt-ai-assistant_access.log
        }
        # Set this path to your site's directory

        # Enable the static file server.

        # Another common task is to set up a reverse proxy:
        # reverse_proxy localhost:8080


        # Or serve a PHP site through php-fpm:
        # php_fastcgi localhost:9000
}

```

.env 檔 (敏感資訊我用 *** 替代)
```
APP_DEBUG=true
APP_URL=
APP_PORT=3000
APP_LANG=zh
APP_WEBHOOK_PATH=/webhook
APP_API_TIMEOUT=30000
APP_MAX_GROUPS=5
APP_MAX_USERS=20
APP_MAX_PROMPT_MESSAGES=100
APP_MAX_PROMPT_TOKENS=1792
APP_INIT_PROMPT=

HUMAN_NAME=
HUMAN_INIT_PROMPT=

BOT_NAME=噓噓鵝
BOT_INIT_PROMPT=
BOT_TONE=
BOT_DEACTIVATED=true

ERROR_MESSAGE_DISABLED=false

VERCEL_TIMEOUT=
VERCEL_PROJECT_NAME=gpt-ai-assistant
VERCEL_TEAM_ID=
VERCEL_ACCESS_TOKEN=
VERCEL_DEPLOY_HOOK_URL=

OPENAI_TIMEOUT=30000
OPENAI_API_KEY=***
OPENAI_COMPLETION_MODEL=gpt-3.5-turbo
OPENAI_COMPLETION_TEMPERATURE=0.9
OPENAI_COMPLETION_MAX_TOKENS=256
OPENAI_COMPLETION_FREQUENCY_PENALTY=0
OPENAI_COMPLETION_PRESENCE_PENALTY=0.6
OPENAI_IMAGE_GENERATION_SIZE=256x256

LINE_TIMEOUT=30000
LINE_CHANNEL_ACCESS_TOKEN=***
LINE_CHANNEL_SECRET=***

SERPAPI_TIMEOUT=30000
```

**Comment by memochou1993** [comment]
@pvt5r486 

反過來操作。

你把這行加回去，其他砍掉。

```
respond "Caddy is Running!"
```

看看 80 port 有沒有正常顯示這行字？

**Comment by memochou1993** [comment]
自動變成 https://pvt5r486.xyz/ 是正常的，因為 80 port 就是預設的 HTTP 埠號。

然後再改回這樣？

```
pvt5r486.xyz
{
        reverse_proxy 127.0.0.1:8000

        log {
                output file /var/log/caddy/gpt-ai-assistant_access.log
        }
}
```

**Comment by pvt5r486** [comment]
@memochou1993 

以下是嘗試建議後的調整
- 設置 `APP_PORT=8080` 後重新運行 `docker-compose up -d`

啟動後得到以下結果
![image](https://user-images.githubusercontent.com/41603487/226505156-1f7ce7e7-26a7-45cf-ba1a-13de883f0c30.png)

接下來是 caddyFile 的調整，移除`反向代理`只`保留 log`
```
pvt5r486.xyz {
        log {
                output file /var/log/caddy/gpt-ai-assistant_access.log
        }
}
```

下 `caddy stop` 後，運行 `sudo systemctl start caddy` 並且透過 `sudo systemctl status caddy` 確認運行狀態

![image](https://user-images.githubusercontent.com/41603487/226505471-dd69bab8-22c2-4b43-b6bb-451a5262639f.png)


接著使用 `curl` 指令來測試有沒有通~
![image](https://user-images.githubusercontent.com/41603487/226506028-afd72e33-4231-4e0e-8f4f-c3353c4d463a.png)

可以看到有些指令下了好像沒有回應..
後來我直接開瀏覽器看，發現沒噴 502 了，拿到 200
[https://pvt5r486.xyz/](https://pvt5r486.xyz/)

然後是容器的 logs
![image](https://user-images.githubusercontent.com/41603487/226506193-9f0d7260-3fa6-474f-9bd5-297290ce2f91.png)

**Comment by memochou1993** [comment]
我的 DNS records：

```
AAAA
www | 172.xxx.xx.xxx

CNAME
gpt-ai-assistant | www.epoch.tw
```

我的 Caddyfile：

```
gpt-ai-assistant.epoch.tw {
    reverse_proxy 127.0.0.1:86

    log {
        output file /var/log/caddy/gpt-ai-assistant_access.log
    }

    tls memochou1993@example.com
}
```

如果真的不行，你把 VPS 密碼 email 給我，我 ssh 進去看看，試完你再把密碼改掉。

**Comment by pvt5r486** [comment]
@memochou1993 
好的，我用 gmail 跟你聯絡，感謝幫忙!

後來我把我的 A 紀錄跟 CNAME 也仿照你的這樣設定，
並且 `APP_PORT` 同樣維持 `8080 `，
防火牆打開設定對應的 port 都開啟，
Caddyfile 也跟你設定快要一致，
訪問 [https://gpt-ai-assistant.pvt5r486.xyz](https://gpt-ai-assistant.pvt5r486.xyz) 還是 502

再麻煩你連線進來幫我看看了

**Comment by memochou1993** [comment]
是 DNS 的問題吧？

我起了一個 Nginx 在 8000 port，容器沒問題，反向代理也沒問題。

用 IP 會通

http://172.105.211.224/

<img width="666" alt="image" src="https://user-images.githubusercontent.com/38420282/226655432-ce7cf564-04b6-4a1d-9712-75f7ce83f224.png">

用 domain name 不通

<img width="537" alt="image" src="https://user-images.githubusercontent.com/38420282/226655115-5c8b0cdf-ec22-415a-b3f2-236a9b1f892a.png">

所以你要檢查 domain name 是不是真的已經讓 linode 的 DNS 託管了

**Comment by memochou1993** [comment]
通了啦！

https://gpt-ai-assistant.pvt5r486.xyz/info

是不是 image 都沒有重建建立，要重新建立喔！

```
docker-compose up -d --build
```

歡迎抖內！

**Comment by pvt5r486** [comment]
哦哦，我好像都沒有加 `--build` 耶，哈哈

我只有關掉然後再重啟...XDD

感覺這一串很值得給別人參考
