### ISSUE TITLE
更新後發問已讀不回

### ISSUE THREAD

**Issue by bryanliao-hi** [memochou1993/gpt-ai-assistant#235]
vercel 後台回報 403錯誤
![螢幕擷取畫面 (42)](https://user-images.githubusercontent.com/58894019/227079008-e0b0440e-e6b3-4eab-ba16-5877ce2d7a87.png)

**Comment by memochou1993** [comment]
原本可以是嗎？

這個 `LINE_CHANNEL_SECRET` 環境變數檢查一下
