### ISSUE TITLE
HUMAN_INIT_PROMPT  跟  BOT_INIT_PROMPT  正確設法為何?

### ISSUE THREAD

**Issue by 8807p3** [memochou1993/gpt-ai-assistant#243]
這兩個我有點搞混.    如果是在 human init 中寫 你是貓咪, 我是主人   是不是就等於 在  bot init  裡面寫  我是貓咪,你是主人呢?

**Comment by memochou1993** [comment]
在 turbo 還沒出來之前，是用 `HUMAN_INIT_PROMPT` 去設定人物

在 turbo 出來之後，因為有了 system role，加了 `BOT_INIT_PROMPT` 去設定人物

現在可以用 `BOT_INIT_PROMPT` 即可！
