### ISSUE TITLE
環境變數改變後? 每次都要重新佈署嗎?

### ISSUE THREAD

**Issue by 8807p3** [memochou1993/gpt-ai-assistant#244]
我目前 環境變數改變, 就會重新佈署一次. 有點繁瑣, 請問這樣操作是正確的嗎? 還是可以不用這樣麻煩, 只要在LINE裡面 下達 restart 指令就可以了?

**Comment by 8807p3** [comment]
我目前 環境變數改變, 就會重新佈署一次.  有點繁瑣, 請問這樣操作是正確的嗎? 還是可以不用這樣麻煩, 只要在LINE裡面 下達  restart 指令就可以了?

**Comment by memochou1993** [comment]
每次改變環境變數都需要重新部署。

若要使用 `restart` 指令，需要另外設定 Vercel deploy webhook。
