### ISSUE TITLE
想要徵求製作教學文章的同意

### ISSUE THREAD

**Issue by wingogo80428** [memochou1993/gpt-ai-assistant#247]
您好，我是一個正開始經營AI香冠議題的小粉專，
目前打算使用您的程式碼作為教學內容，
想徵詢您的同意。

感謝！

**Comment by wingogo80428** [comment]
> 您好，我是一個正開始經營AI相關議題的小粉專， 目前打算使用您的程式碼作為教學內容， 想徵詢您的同意。
> 
> 感謝！

**Comment by memochou1993** [comment]
可以喔！
