### ISSUE TITLE
機器人沒有回應

### ISSUE THREAD

**Issue by Harry-py** [memochou1993/gpt-ai-assistant#248]
你好，謝謝你們的project！很有趣也很有用。
我依照文字説明安裝了之後，發現不管講什麽機器人都不會回應也不會已讀。
<img width="184" alt="image" src="https://user-images.githubusercontent.com/66230476/230751016-f3033d55-0db1-4f8c-b2ed-cc517fd28116.png">

每次傳給他一則訊息，vercel會跳出這個log（上面第一個error log）：
<img width="868" alt="image" src="https://user-images.githubusercontent.com/66230476/230750859-dbe43223-bbfb-4913-a2aa-f384ca52f7e3.png">

在自己的local PC嘗試debug（使用ngrok）后發現，看來是Line有確實傳POST request到正確的webhook URL，但是server沒有回應。
<img width="891" alt="image" src="https://user-images.githubusercontent.com/66230476/230751072-b2d598fc-a65a-4701-bd0c-af195f44e7d2.png">

<img width="881" alt="image" src="https://user-images.githubusercontent.com/66230476/230751084-1cb30e76-e5c6-49a2-862d-8b1d7754a39b.png">

<img width="902" alt="image" src="https://user-images.githubusercontent.com/66230476/230751091-c1404466-2ba1-4b34-a453-549addc8b926.png">

發現app.post這個function都沒有被執行到。好像都沒有聽到event：
`app.post(config.APP_WEBHOOK_PATH ,validateLineSignature, async (req, res) => {
  try {
    console.log("1: message caught with no error.")
    await storage.initialize();
    await handleEvents(req.body.events);
    res.sendStatus(200);
  } catch (err) {
    console.error(err.message);
    res.sendStatus(500);
  }
  if (config.APP_DEBUG) printPrompts();
});`

想請問有人有類似情況嗎？這可能是什麽問題？謝謝。

**Comment by memochou1993** [comment]
只打「你好」也沒有回應嗎？

**Comment by i3c** [comment]
這裡也有看到 LOG Error 是 504, LINE 只打 "你好" 也沒反應, 沒有詳細下去看是否其它 error detail 和樓主相同, 這個情況已經好幾天了, 前陣子剛開始有問題的時候有試著 update github fork 的 code, 但是沒幫助. issue still there.

**Comment by memochou1993** [comment]
@Harry-py 

你的 `/webhook` 是 404 錯誤，代表路徑可能是錯的，檢查一下？

**Comment by memochou1993** [comment]
@i3c

504 應該就是超時了，你的 OpenAI 有填入付款資訊嗎？

**Comment by i3c** [comment]
> @i3c
> 
> 504 應該就是超時了，你的 OpenAI 有填入付款資訊嗎？
@memochou1993 

我沒有填入付款資訊，不過我的 Free trial usage 時間是到 2023/06/01 還沒有到期，usage 餘量也還很多。

如果是付款資訊沒填的原因，那用手機 safari 開的時候，若是選擇 Apple Pay 付款使用 Pro版本，OpenAI 留存資料裡的付款資訊的卡號等等一樣維持未填，是否也有可能造成 API 串接 504超時?
(不想將信用卡號留在 OpenAI 系統內, 所以考慮用 Apple Pay)

**Comment by Harry-py** [comment]
抱歉這麽晚才回應。目前已經沒有這個問題了。
code的部分我全都沒有動，也沒有重新deploy，今天504 error就自己消失了。(我前面ngrok那邊請忽略)
目前可以正常跟機器人對話，無論是問問題還是打“你好”都行。我也沒有信用卡號在OpenAI，就是用免費credit這樣。
沒有發現是哪個節點導致超時問題，如果有新發現會再跟你們説。

**Comment by wenchelu365** [comment]
> 抱什麼晚上才回复。目前已經沒有這個問題了。 代碼的部分我全部沒有動，也沒有重新部署，今天504錯誤就自己消失了。（我之前面ngrok那邊請忽略)目前可以正常跟機器人對話 ，無論是問題還是打“你好”都行。我在OpenAI也沒有信用卡，就是使用免費credit這樣的。沒有發現是 哪個節點導致超時問題，比如果有新發現會再跟你們說。

請問您後來有使用vercel付費方案嗎?我遇到的問題跟你一模一樣QQ..

**Comment by i3c** [comment]
@wenchelu365 
code 的部份我也是沒動, vercel, OpenAI API 也還是用免費，504也過一陣就消失，但是詢問次數和頻率一高還是有機會碰到沒反應。我這裡判斷應該是vercel, OpenAI API 因為是免費，所以有可能在被排到優先權比較低才會 timeout, 或者是當下可能太多人用。
不過上面這些屬於猜測，我沒有試過轉付費版本 vercel, OpenaAI API 的情況是不是就不會碰到 timeout，有轉付費版使用的朋友也請提供使用經驗。謝謝。
