### ISSUE TITLE
Request failed with status code 429

### ISSUE THREAD

**Issue by sunrise1748** [memochou1993/gpt-ai-assistant#25]
您好，目前AI只會回覆"Request failed with status code 429"，我有到vercel平台上看到因為錯誤而達到default limit of 1000 concurrent executions的上限，故想請問目前該如何進行除錯，謝謝

![error](https://user-images.githubusercontent.com/59818909/207754603-8f1eb90c-4b67-422f-9be5-f35da088e875.jpg)

**Comment by sunrise1748** [comment]
補上vercel平台上的訊息，謝謝

![image](https://user-images.githubusercontent.com/59818909/207755121-478c8f75-ca1a-425c-bbd8-094710ebe511.png)

**Comment by memochou1993** [comment]
@sunrise1748

有加到群組嗎？

**Comment by sunrise1748** [comment]
有加過，但隨即移除群組

Memo Chou ***@***.***>於 2022年12月15日 週四，10:58寫道：

**Comment by memochou1993** [comment]
@sunrise1748 

幫我看一下 OpenAI 的使用額度

**Comment by sunrise1748** [comment]
OpenAI 額度確實已額滿，故我重新辦了新的OpenAI 帳號並重產API KEY。目前在vercel平台換了新的API KEY，也重新Rebuild但還是一樣的錯誤訊息Request failed with status code 429，附上目前新OpenAI帳號的額度

![image](https://user-images.githubusercontent.com/59818909/207767459-e9834462-2fdf-4a7e-8273-b5b0c324c06d.png)

**Comment by memochou1993** [comment]
@sunrise1748 

有用新的手機註冊嗎？

**Comment by sunrise1748** [comment]
OpenAI 帳號的部分沒有使用手機註冊，只有換個新Email註冊，還是我其他需要用手機註冊的平台、先換隻手機註冊試試看?

**Comment by memochou1993** [comment]
它的額度是綁手機的，幫我換個手機註冊看看，謝謝！

**Comment by sunrise1748** [comment]
好的，我換個手機號試試看，謝謝

**Comment by sunrise1748** [comment]
經過測試，確實是OpenAI的額度導致引起。

這次排除問題中的困難點，OpenAI可使用同一組手機號碼建立新帳號，但這組新帳號並不會顯示正確的使用額度(Free trial usage仍顯示使用0)。故不曉得這點是否為避免濫用建立帳號來刷額度，是有意或真的Bug?

已上總結，再次謝謝您的幫忙
