### ISSUE TITLE
機器人只有已讀沒有回覆

### ISSUE THREAD

**Issue by sailorjenny** [memochou1993/gpt-ai-assistant#251]
照步驟安裝之後，問問題常常沒回應，只有已讀，到Vercel看log出現Error#504，請問有什麼方式可以改善嗎? 感謝

**Comment by Triple-Xxx** [comment]
麻煩請問您是如何解決504的問題的呢，我也遇到相同情況，謝謝

**Comment by sailorjenny** [comment]
@Triple-Xxx 問比較簡單的問題好像就會回覆，翻譯/查天氣之類的就可正常回覆，其他問題也是會一直出現504。因為感覺可以tracking #248 這條就先關了，謝謝你。
