### ISSUE TITLE
錯誤429

### ISSUE THREAD

**Issue by iamginger** [memochou1993/gpt-ai-assistant#252]
![Image 2023-4-13 at 10 51 AM](https://user-images.githubusercontent.com/130618338/231635915-3ade7bb2-1a8b-482e-84f1-14198602f318.jpg)
 Request failed with status code 429
 You exceeded your current quota, please check your plan and billing details.

步驟非常清楚，很容易安裝，很感謝，然而，應該是在生成API key的時候，做錯了什麼？
也可能是在設定 Vercel 專案環境變量這一段，在還沒有做完三組設定的時候，曾經按下了deploy，
但是覺得不對，又回頭把三組設定走一遍。
現在安裝在line上面雖呈現已讀，但是，就是一直出現圖片上的回覆，不知道該怎麼修正？

**Comment by memochou1993** [comment]
請檢查 OpenAI 的 API 額度！
