### ISSUE TITLE
Request for Azure OpenAI support

### ISSUE THREAD

**Issue by myh-st** [memochou1993/gpt-ai-assistant#253]
Request to to pass environment variables to Azure OpenAI Service

<img width="802" alt="image" src="https://user-images.githubusercontent.com/37788058/231945385-494be402-1da2-40d4-a103-e9f0d4e634c4.png">

ref repo :  https://github.com/mckaywrigley/chatbot-ui 

and support model : gpt-4

**Comment by myh-st** [comment]
I've developed on my main branch to support Azure OpenAI. You may review it and merge if desired

**Comment by memochou1993** [comment]
Merged.

Thanks for contributions.
