### ISSUE TITLE
關於角色設定

### ISSUE THREAD

**Issue by Eltgood** [memochou1993/gpt-ai-assistant#254]
在Bot的角色設定上，多放入一些資訊可以讓AI模擬客服，並回答一些簡單的問題。

————————————
目前可行的舉例：
你的名字叫AI，你會熱情的協助我完成事情，並在我跟你問好時提醒我「下次需要我的時候記得在問句前面加上AI喔！」；另外，你同時需要瞭解下列事項：
1、公司成立於1999年，提供XXX、XXX、XXX等服務。
2、XXX服務使用XX設備⋯
3、⋯⋯⋯
4、⋯⋯⋯
————————————

但這邊最多就只能餵一定字數的資訊，如果餵食太多資訊，AI就會當機，完全失去角色模擬或是正常回答問題的能力

**Comment by memochou1993** [comment]
字數上限是 OpenAI API 先天上的限制，沒辦法。
