### ISSUE TITLE
AI 回覆訊息的長度

### ISSUE THREAD

**Issue by Eltgood** [memochou1993/gpt-ai-assistant#255]
要怎麼樣才能讓AI回覆比較長的訊息，而不需要一直點繼續呢？

![Uploading 52B6B168-8E5A-4E20-AF15-33CA4B2DE610.png…]()

**Comment by Eltgood** [comment]
![2E6067D2-68B4-4B5B-A4C2-3F423E22F126](https://user-images.githubusercontent.com/130895133/232520355-e9c75461-d06c-4b1c-af6f-0181358e71c4.png)

**Comment by Eltgood** [comment]
把 OPENAI_COMPLETION_MAX_TOKENS 改成 2048 解決了

**Comment by Elsmei** [comment]
請問這個要如何改?
