### ISSUE TITLE
使用 ai 指令，回覆變得很奇怪

### ISSUE THREAD

**Issue by kingofchengyi** [memochou1993/gpt-ai-assistant#26]
你好，想請問已經照著步驟，但和賴AI聊天目前只得到「Request failed with status code 429 」的回覆，點開「View Function Logs」得到只有以下截圖的資訊：

<img width="1261" alt="截圖 2022-12-15 上午11 22 43" src="https://user-images.githubusercontent.com/50443759/207765027-c55fa5a1-c3d0-4ba2-9fcc-f72e1b211d28.png">

謝謝您撥空解答了～

**Comment by memochou1993** [comment]
@kingofchengyi 

請問你是什麼時候部署好的呢？

另外，可以幫我看 OpenAI 的使用額度嗎？

**Comment by bluesway** [comment]
我十分鐘前剛 sync 最新的 code，目前也會經常遇到 429 error，而且回應變得很奇怪
![圖片](https://user-images.githubusercontent.com/2682259/207769230-2783b93e-f30e-4f99-8d22-9fcfd7bd6fd6.png)
![圖片](https://user-images.githubusercontent.com/2682259/207769262-3569fd0e-354b-4ce3-8df2-403b2967d50b.png)

**Comment by memochou1993** [comment]
@bluesway

回應真的變得很怪，我的天

我知道問題在哪裡了，因為 `ai` 這個指令也被它讀進去了

我修復一下

**Comment by bluesway** [comment]
我在 LINE 的後台先把 webhook URL rollback 到 vercel 上昨天的版本，但還是會一直吐奇怪的訊息，感覺被玩壞了...
![圖片](https://user-images.githubusercontent.com/2682259/207773601-eb09a709-81a3-4063-ab93-ac09ece41716.png)

**Comment by memochou1993** [comment]
@bluesway

更新了一個  `1.0.10` 的版本上去，可以幫忙試試看嗎？

**Comment by bluesway** [comment]
情況還是一樣，試著建了新的 line bot 排除任何可能的 cache 問題，也沒有改善
<img width="376" alt="圖片" src="https://user-images.githubusercontent.com/2682259/207782835-31af9edb-5a9d-4f24-8df7-764e1eb2827e.png">

**Comment by bluesway** [comment]
@memochou1993 抓到問題點了，我一直用的都是 code-davinci-002 這個 model，剛剛改成 text-davinci-003 之後就一切正常了
<img width="382" alt="圖片" src="https://user-images.githubusercontent.com/2682259/207783648-ff93fd57-2554-44b9-84e3-731de4918d06.png">

**Comment by memochou1993** [comment]
@bluesway 

原來如此！你是用環境變數指定的對嗎？

竟然發瘋，哈哈

**Comment by bluesway** [comment]
@memochou1993 對啊，用環境變數指定的

回到 ai 指令的部份，目前發現用 --auto-reply off 關掉自動回復後，過段時間又會自己重新打開

**Comment by memochou1993** [comment]
@bluesway 

這中間有沒有重新部署過呢？

**Comment by memochou1993** [comment]
@bluesway

更新到 1.0.11 看看，謝謝！
