### ISSUE TITLE
Support fine-tuned model

### ISSUE THREAD

**Issue by nuka10933** [memochou1993/gpt-ai-assistant#260]
我已經自己訓練好、微調好自己的gpt模型了 請問怎麼加進作者大大您的程式碼 讓我的微調模型也能在line裡的gpt呈現出來 謝謝

**Comment by memochou1993** [comment]
@nuka10933

試試看把 `OPENAI_COMPLETION_MODEL` 改成你的 model 名稱呢？

```
OPENAI_COMPLETION_MODEL=FINE_TUNED_MODEL
```
