### ISSUE TITLE
缺少 SERPAPI_API_KEY 環境變數

### ISSUE THREAD

**Issue by kress64** [memochou1993/gpt-ai-assistant#261]
Vercel 有核對過key 的值也有做redeploy, AI 還是一直說缺少環境變數,不知問題在哪..請賜教
![image](https://github.com/memochou1993/gpt-ai-assistant/assets/132585866/02c06172-f2d5-49b2-867e-07c853c28582)
![image](https://github.com/memochou1993/gpt-ai-assistant/assets/132585866/3bb6b105-ff4e-4686-bf66-f0473ff62fd7)

**Comment by memochou1993** [comment]
@kress64 

請問你有重新部署嗎？

**Comment by memochou1993** [comment]
@kress64 

請幫我先刪除環境變數，然後再重新填寫一次，並且重新部署。

**Comment by kress64** [comment]
> @kress64
> 
> 請幫我先刪除環境變數，然後再重新填寫一次，並且重新部署。

有刪掉SERPAPI_API_KEY 這行,重新填寫加回去和重新佈署了, 還是一樣不行...

**Comment by memochou1993** [comment]
@kress64 

把 Vercel Project 刪除，重新試一次看看。

**Comment by kress64** [comment]
> @kress64
> 
> 把 Vercel Project 刪除，重新試一次看看。

感謝
除了vercel 有重新建立project, 後來發現Line developer 那邊也有一個地方的設定好像不對因此也有修改, 現在要AI 搜尋已不會再報錯了也有給回應
