### ISSUE TITLE
Empty role of message

### ISSUE THREAD

**Issue by mccoysc** [memochou1993/gpt-ai-assistant#262]
as the pic.
![image](https://github.com/memochou1993/gpt-ai-assistant/assets/18025276/3af6a5c8-3dac-4f4f-95e0-a9312c1ac4f2)

提前打预防针：不要觉得与“图片”这种消息类型有什么关系，完全无关，文字消息一样出问题。

![image](https://github.com/memochou1993/gpt-ai-assistant/assets/18025276/03e62288-d581-4ba9-9d71-cfea09d58fdb)

**Comment by memochou1993** [comment]
@mccoysc 

感謝回報。

有點重現不出來，可以提供更多線索嗎？

什麼情況下會出現這樣的錯誤？

**Comment by mccoysc** [comment]
任何情况都可能引发这个问题，可以加这个bot自己测试：https://liff.line.me/1645278921-kWRPP32q/?accountId=793shpyj

**Comment by memochou1993** [comment]
@mccoysc 

已加入好友，並成功聊天。

但是在想，要如何重現呢？
