### ISSUE TITLE
Cant verify webhook URL

### ISSUE THREAD

**Issue by vvxxii** [memochou1993/gpt-ai-assistant#267]
![Screenshot_20230522_153143](https://github.com/memochou1993/gpt-ai-assistant/assets/58267389/6763553c-8df9-4b33-be6e-e2d68b657efd)
tried creating the project twice, same error

**Comment by memochou1993** [comment]
Please check out the [doc](https://memochou1993.github.io/gpt-ai-assistant-docs/questions.html#為什麼-line-平台會出現-404-錯誤).

**Comment by vvxxii** [comment]
Docs solution for this error is to check the URL, i checked them all of those given on Vercel, none of them can be verified.

**Comment by xiaowei0605** [comment]
403填写的是LINE_CHANNEL_SECRET，也还是不成功不知道为什么？
