### ISSUE TITLE
Request failed with status code 429

### ISSUE THREAD

**Issue by Harry0406** [memochou1993/gpt-ai-assistant#271]
BOY 回復:
POST https://api.openai.com/v1/chat/completions
Request failed with status code 429
You exceeded your current quota, please check your plan and billing details.

可能是額度滿了?
有嘗試使用另一隻手機號碼註冊OpenAI還產生KEY，在部屬部分已經亂掉不知道怎麼改KEY

**Comment by JIM90108** [comment]
文件在哪裡
