### ISSUE TITLE
如何串接 Azure OpenAI

### ISSUE THREAD

**Issue by linsanity8614** [memochou1993/gpt-ai-assistant#272]
已知串接Azure openai 需要用到端點(AZURE_OPENAI_ENDPOINT)及金鑰(AZURE_OPENAI_KEY)
但不知道要怎麼樣修正使其正確連結

**Comment by memochou1993** [comment]
修改 `OPENAI_BASE_URL` 環境變數，例如 `https://<endpoint>.openai.azure.com`

我自己是沒試過，可以試試看。

或參考相關議題：https://github.com/memochou1993/gpt-ai-assistant/issues/253
