### ISSUE TITLE
圖畫功能有畫錯

### ISSUE THREAD

**Issue by CubeComputerLab** [memochou1993/gpt-ai-assistant#280]
圖畫功能有畫錯(輸入:請畫一隻烏龜時 畫錯)
![84564](https://github.com/memochou1993/gpt-ai-assistant/assets/132181777/9b85d9ca-b5c2-4767-a2ef-38ec98aac078)

**Comment by memochou1993** [comment]
GPT 中文不好，試試看用英文！
