### ISSUE TITLE
OpenAI 已不提供免費額度了嗎？

### ISSUE THREAD

**Issue by hades26** [memochou1993/gpt-ai-assistant#282]
今天用了半天，一直說

POST https://api.openai.com/v1/chat/completions
Request failed with status code 429
You exceeded your current quota, please check your plan and billing details.

都沒成功，幾個月前申請的帳號有18美金，今天因為安裝gpt-ai-assistant才發現過期，於是重新申請了一個帳號，竟然沒有18美金試用了，直接變成0美金，要用必須付錢了...
可惜啊~gpt-ai-assistant就不能用了

**Comment by memochou1993** [comment]
@hades26 

有用其他手機號碼試試看嗎？
