### ISSUE TITLE
如何SerpApi輸出今日股價

### ISSUE THREAD

**Issue by 1117iyu** [memochou1993/gpt-ai-assistant#285]
<img width="720" alt="image" src="https://github.com/memochou1993/gpt-ai-assistant/assets/71537490/73bb880e-d794-4484-9665-fbe915b71699">

打開html網也確實是台積電股價，但ai卻回

<img width="225" alt="image" src="https://github.com/memochou1993/gpt-ai-assistant/assets/71537490/3159ecd9-a352-424c-90ac-3a58895c5d09">

**Comment by memochou1993** [comment]
關鍵字是 `查詢`，檢查一下是不是打到 `査詢` 了？
