### ISSUE TITLE
錯誤訊息提問

### ISSUE THREAD

**Issue by Fox5091** [memochou1993/gpt-ai-assistant#287]
詢問問題後會出現以下錯誤訊息想請問是哪裡出了問題嗎
POST https://api.openai.com/v1/chat/completions
Request failed with status code 429
You exceeded your current quota, please check your plan and billing details.

**Comment by memochou1993** [comment]
@Fox5091 

沒有額度了～

需要填寫信用卡號！

**Comment by Andrew53O** [comment]
@Fox5091 
可以檢查openai api 的 消費， 鏈接 = [Usage](https://platform.openai.com/account/usage)

我也是在這邊卡了很久

如果您是使用你的chatgpt 帳號很有可能會發生這樣， 因爲Openai api 的免費使用只有前三個月。 

**解決方法** = 建立新的帳號

我的主要帳號的免費使用, 已經在二月份過期了，:)
![Main account usage](https://github.com/memochou1993/gpt-ai-assistant/assets/96643896/ca58afbe-5110-43fe-808f-579399455585)


其他資源：
現在的免費使用變成5塊美金， 以前是18快美金

![Info from Community](https://github.com/memochou1993/gpt-ai-assistant/assets/96643896/711e73bb-e2d9-4771-b1b9-1351d08c69b9)
[Link](https://community.openai.com/t/how-can-i-get-free-trial-credits/26742/26?page=2)

是的，它不僅僅是 5 美元。 以前是 18 美元，我們的內部數據顯示，人們可以用 5 美元進行約 750 次 API 調用，這足以讓人們了解如何使用 API（這是免費試用積分的全部目標）。

**另請注意，您只能獲得與您的電話號碼關聯的第一個帳戶的免費積分。 後續帳戶不會獲得免費積分**
