### ISSUE TITLE
不能「繼續」答案

### ISSUE THREAD

**Issue by Andrew53O** [memochou1993/gpt-ai-assistant#288]
![image](https://github.com/memochou1993/gpt-ai-assistant/assets/96643896/8797d532-1e21-4152-abbc-c25ecc23fb95)

請問一下， 只能用 "/continue" 來繼續回答嗎？ “繼續"按鍵好像用不了呢

![image](https://github.com/memochou1993/gpt-ai-assistant/assets/96643896/3f54d886-9ff0-48ec-8b12-c3486ed8ae4c)

**Comment by memochou1993** [comment]
每一次都不行嗎？

**Comment by Andrew53O** [comment]
以前我是都不行呢， 但我剛試了， 答案有點奇怪

![image](https://github.com/memochou1993/gpt-ai-assistant/assets/96643896/4c4b494b-149a-4fb6-9586-64d1954e0413)

**Comment by memochou1993** [comment]
用「忘記」清楚它的上下文，試試看其他對話情境

**Comment by Andrew53O** [comment]
感謝， 可以了
