### ISSUE TITLE
翻譯指令無效疑問

### ISSUE THREAD

**Issue by cdcd72** [memochou1993/gpt-ai-assistant#289]
看起來 4.7.1 版本的相關翻譯指令均無法使用...

![image](https://github.com/memochou1993/gpt-ai-assistant/assets/24297780/958e40dc-8518-452d-ba21-504a53484128)

如上圖，沒有後續回覆...

我稍微看了下，看起來連 API 都沒發出去，但看不太明白原因為何...

補上 4.7.0 版本以下的行為

![image](https://github.com/memochou1993/gpt-ai-assistant/assets/24297780/3b6ccdbb-f57c-4df9-96bb-1a7c3175bc8d)

**Comment by memochou1993** [comment]
@cdcd72 

已修正，感謝回報
