### ISSUE TITLE
The auto-reply is not turned off completely

### ISSUE THREAD

**Issue by memochou1993** [memochou1993/gpt-ai-assistant#29]
- the `--auto-reply off` command is not turned off completely

**Comment by bluesway** [comment]
@memochou1993 for 1-on-1 chat, the storage implementation works
![圖片](https://user-images.githubusercontent.com/2682259/208033977-35360b89-7347-4302-83c9-0be84d7fe74f.png)

However, in a group chat, seems doesn't work still
![圖片](https://user-images.githubusercontent.com/2682259/208034088-f1fadbac-3623-4171-84a9-bfcd312a6d98.png)

**Comment by memochou1993** [comment]
@bluesway 

Thanks for reporting!

I never try that situation.

So glad you saw the storage implementation. It took a lot of effort.

Reopened this issue.

**Comment by memochou1993** [comment]
@bluesway 

Seems Ok after 30 mins.

Could you test it again please?

![image](https://user-images.githubusercontent.com/38420282/208058001-0f3fb0a4-0893-4fbe-ae51-6259adf69682.png)

**Comment by jwliang1226** [comment]
I have tested it, auto-replay will fail in group. 
Maybe it takes more than one person to talk to him to find out.

**Comment by bluesway** [comment]
I found 1-on-1 also failed after another hours for previous version, check the time; will try the latest version now
![圖片](https://user-images.githubusercontent.com/2682259/208063102-1e45f584-1e53-45b6-b5ec-dfb7fe3775d3.png)

**Comment by memochou1993** [comment]
@jwliang1226

Thanks for testing

Which version do you use?

**Comment by bluesway** [comment]
@memochou1993 it was 1.0.11, now deployed with 1.1.0 will keep monitoring

**Comment by jwliang1226** [comment]
@memochou1993 
it was 1.1.0 before 4 hours.

**Comment by bluesway** [comment]
on setting auto reply off with 1.1.0, will it apply to all sessions, that says, different chats/groups?
I set to off in chatA (1-on-1 chat), and it will not respond without ai command in chatB (group chat)

**Comment by memochou1993** [comment]
Different chat group should share one storage, so it should apply to all sessions.

Could you check the `APP_STORAGE` environment variable  on Versel.

What does it like now?

**Comment by jwliang1226** [comment]
There are only three environment variables.
OPENAI_API_KEY , LINE_API_KEY , LINE_API_SECRET
Where is APP_STORAGE?

**Comment by memochou1993** [comment]
@jwliang1226 

I see!

Please check the latest doc [here](https://github.com/memochou1993/gpt-ai-assistant#%E6%8C%87%E4%BB%A4).

Create a Vercel access token and add a environment variable named `VERCEL_API_KEY` on project settings.

Sorry, I forgot to mention that!

I'll update the release notes in the future.

**Comment by memochou1993** [comment]
@jwliang1226 @bluesway 

Oh...I found the bug in the storage finally.

Version 1.1.1 is now released.

I would appreciate it very much if you guys update and test it again.

Thanks.

**Comment by bluesway** [comment]
@memochou1993 so far so good, nice work! 👏
