### ISSUE TITLE
關於指令觸發方式的問題

### ISSUE THREAD

**Issue by waynesung** [memochou1993/gpt-ai-assistant#292]
之前，指令的關鍵字，是擺在開頭才會觸發，但是最近發現，指令會被對話中的內容觸發：
例如：
『調整畫面解析度』之前這個句子並不會觸發繪圖指令。
『剛剛忘記拿東西』之前這個句子並不會觸發忘記的指令。
這個情況出現在目前所有的指令上，您是否能夠幫我確認一下這個情況的原因。
或者，是否有可能進行一些修改（例如賦予這些指令一個總開關等）。

非常感謝！

**Comment by memochou1993** [comment]
@waynesung 

感謝回饋。

新版本把判斷指令的方式改回來了。

現在要以關鍵字開頭才會被判斷成是指令。
