### ISSUE TITLE
想請教在vercel部屬發生錯誤

### ISSUE THREAD

**Issue by CJ1031** [memochou1993/gpt-ai-assistant#296]
在執行部屬時，顯示500: INTERNAL_SERVER_ERROR錯誤
排錯時，新增環境設定VERCEL_CLI_VERSION、VERCEL_PROJECT_NAME專案名稱不一致
![image](https://github.com/memochou1993/gpt-ai-assistant/assets/87159303/fb29e4b3-d5c5-4381-848f-db3bcfc4d0aa)

重新部屬後，內容顯示版本，Webhook URL驗證失敗
![image](https://github.com/memochou1993/gpt-ai-assistant/assets/87159303/dfb4a5a1-ba25-421f-a8d5-c758be91a7a6)

附上錯誤訊息
![image](https://github.com/memochou1993/gpt-ai-assistant/assets/87159303/7b64c451-79bc-4f54-b6ad-3be3a21a8b2a)

請問是我部屬時，漏掉哪個環節
再請協助 謝謝

**Comment by memochou1993** [comment]
@CJ1031 

這一頁看得到版本資訊，就代表應用程式應該是部署成功的。

https://gpt-ai-assistant-emp9coflt-cj1031s-projects.vercel.app/

可以檢查一下 Webhook URL 是否正確，是否有加上 `/webhook` 後綴。

或者截圖一下驗證失敗的畫面提供參考。

**Comment by CJ1031** [comment]
非常感謝  問題已排除，重新設定Webhook URL就正常了
