### ISSUE TITLE
除了打招呼用語、指令、畫圖之外，其他的都已讀不回

### ISSUE THREAD

**Issue by Meiyasa** [memochou1993/gpt-ai-assistant#297]
您好，看起來是有串接成功，但是除了除了打招呼用語/指令/畫圖之外，其他的都已讀不回，有看到前面問題的回覆，後來也加上了環境變數VERCEL_CLI_VERSION = vercel@32.2.5，chatcpt也已開啟api付費，但是還是已讀不回，API key都顯示未使用
![image](https://github.com/memochou1993/gpt-ai-assistant/assets/128664588/3c48327a-b241-46ba-96cf-0deaabcabc5f)
![image](https://github.com/memochou1993/gpt-ai-assistant/assets/128664588/0271cdc0-15fa-417f-ab22-0356f1e1413a)
![image](https://github.com/memochou1993/gpt-ai-assistant/assets/128664588/34f0a0b9-ce7d-4900-a4cd-d217a7013bc9)

**Comment by memochou1993** [comment]
@Meiyasa 

不確定是不是呼叫超時。

如果只打「嗨」會有回應嗎？

**Comment by simpson918112** [comment]
目前狀況也是遇到，會已讀不回，請看圖片，謝謝。
![螢幕擷取畫面 2023-10-14 193036](https://github.com/memochou1993/gpt-ai-assistant/assets/147915618/fb6e1ade-6378-4000-a778-895e6fb4294c)

**Comment by memochou1993** [comment]
@simpson918112 

請參考這個：

https://memochou1993.github.io/gpt-ai-assistant-docs/questions.html#為什麼-vercel-平台中出現-504-錯誤
