### ISSUE TITLE
指定 fine-tuned 模型

### ISSUE THREAD

**Issue by profwu** [memochou1993/gpt-ai-assistant#298]
請問如何指定gpt model為自己fine tune後的模型?
要在那一隻程式的哪一個地方修改呢?

**Comment by memochou1993** [comment]
@profwu 

嗨。

我沒有試過，你可以試試看。

你是用 OpenAI 還是 Azure？

你的 fine-tune 完的模型，是否有得到 API 端點？

不確定是不是修改 `OPENAI_BASE_URL` 就好。

相關連結：

- https://github.com/memochou1993/gpt-ai-assistant/issues/272#issuecomment-1575664359
- https://memochou1993.github.io/gpt-ai-assistant-docs/environments.html#%E4%B8%80%E8%A6%BD

**Comment by profwu** [comment]
Hi,

我用的是openai的fine tune。我在Environment variable設定OPENAI_COMPLETION_MODEL=我的model名稱
然後在line中會出現這樣錯誤

POST https://api.openai.com/v1/completions
Request failed with status code 404
This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?

**Comment by memochou1993** [comment]
@profwu 

你的 fine-tune 完的模型，是否有得到 API 端點？

**Comment by tonylmm** [comment]
想請教一下，在openai中的fine tuning後，並非得到api的端點，而只有得到一個模型的新名稱，像這樣ft:gpt-3.5-turbo-0613:personal::8ArgcXXX和job id像這樣ftjob-7ZZQFjR3ENWpyTo5c0JWuXXX。不知道該如何在您建構的這個LineBot中作使用???

**Comment by tonylmm** [comment]
> @tonylmm
> 
> 修改 Vercel 的環境變數：
> 
> ```
> OPENAI_COMPLETION_MODEL=ft:gpt-3.5-turbo:my-org:custom_suffix:id
> ```

非常感謝您的回覆，在下受益良多。
但嘗試在Vercel的環境變數中，加入了自己的model id後，也是得到像上面朋友的結果，
POST https://api.openai.com/v1/completions
Request failed with status code 404
This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?
不知道問題出在那裏???

**Comment by memochou1993** [comment]
@tonylmm 

感謝回報。

請拉 4.8.0 版，然後再試一次看看。

**Comment by tonylmm** [comment]
太感謝您了，果然用4.8.0的版本就可以了呢，辛苦您了。

**Comment by profwu** [comment]
請問怎樣變成4.8.0版本呢？


Memo Chou ***@***.***> 於 2023年12月8日 週五 00:45 寫道：
