### ISSUE TITLE
Chat Gpt chat doesn't have answer and seems to timeout

### ISSUE THREAD

**Issue by JHunlimited-LLC** [memochou1993/gpt-ai-assistant#301]
Hi there, I hope you are well. 
 I just forked the latest version and deployed without issue. I followed instructions and seem to have Issues with incomplete completions/responses and non-replies from OpenAI. Is there an optimal configuration I need to have? The errors I get are not very clear.
The error message I see is below. I get many success with response 200 but nothing comes to chat window.

Time
November 19 05:25:01.62 GMT-05:00
Request Path
/webhook
Status Code
504
Host
gpt-ai-assistant-chi-seven-68.vercel.app
Request ID
25ntb-1700389501621-64a7ba40c3cc
Request User Agent
LineBotWebhook/2.0
Level
Error

Environment
production
Branch
main
Type
Serverless Function

Function
/api
Memory Used / Limit
94 MB / 1024 MB

**Comment by memochou1993** [comment]
@JHunlimited-LLC 

Hi.

Could you provide some screenshots and your deployed app domain.

Thanks.

**Comment by JHunlimited-LLC** [comment]
Hi Please see attached.
![Screenshot 2023-11-22 194048](https://github.com/memochou1993/gpt-ai-assistant/assets/26065107/ec4fd7da-1b6f-4377-8419-c1fcadb5d7ac)
![Screenshot 2023-11-22 194845](https://github.com/memochou1993/gpt-ai-assistant/assets/26065107/36df843b-b748-4346-8cf5-7ae9222a0cb6)
![Screenshot 2023-11-22 194632](https://github.com/memochou1993/gpt-ai-assistant/assets/26065107/2dad3246-5207-41dc-afa6-7094977335c3)
