### ISSUE TITLE
Vercel Timeout

### ISSUE THREAD

**Issue by JHunlimited-LLC** [memochou1993/gpt-ai-assistant#302]
Hi this is in reference to your question in a previous issue that got closed for some reason.
Can you help?
Please see attached.
![Screenshot 2023-11-22 194048](https://github.com/memochou1993/gpt-ai-assistant/assets/26065107/ec4fd7da-1b6f-4377-8419-c1fcadb5d7ac)
![Screenshot 2023-11-22 194845](https://github.com/memochou1993/gpt-ai-assistant/assets/26065107/36df843b-b748-4346-8cf5-7ae9222a0cb6)
![Screenshot 2023-11-22 194632](https://github.com/memochou1993/gpt-ai-assistant/assets/26065107/2dad3246-5207-41dc-afa6-7094977335c3)
https://github.com/memochou1993/gpt-ai-assistant/issues/301#issue-2000793496
_Originally posted by @JHunlimited-LLC in https://github.com/memochou1993/gpt-ai-assistant/issues/301#issuecomment-1823704033_

**Comment by memochou1993** [comment]
@JHunlimited-LLC 

Hi, unless you have purchased Vercel's Team Plan, you will encounter a timeout limit of 10 seconds.

If you are on the free plan, you can reduce the size of messages sent to the AI.

```
APP_MAX_PROMPT_MESSAGES = 4
APP_MAX_PROMPT_TOKENS = 256
OPENAI_COMPLETION_MAX_TOKENS = 64
```
