### ISSUE TITLE
500: INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by kozaka01** [memochou1993/gpt-ai-assistant#303]
I have tried several solutions, but they have not worked. How can I solve this?
![IMG_0027](https://github.com/memochou1993/gpt-ai-assistant/assets/152618862/63a77698-b989-40e4-a464-93ca65325a2f)
![IMG_0024](https://github.com/memochou1993/gpt-ai-assistant/assets/152618862/2b5a5f9b-4411-42e5-ae9b-edfb3cc6a611)

**Comment by memochou1993** [comment]
Try this

https://github.com/memochou1993/gpt-ai-assistant/issues/295#issuecomment-1741986240
