### ISSUE TITLE
HTTP回應404

### ISSUE THREAD

**Issue by wk9480** [memochou1993/gpt-ai-assistant#307]
請問一下
目前的情形是
在line 裡面webhook URL輸入完之後點選驗證回覆404

The webhook returned an HTTP status code other than 200.(404 Not Found)

Confirm that your bot server returns status code 200 in response to the HTTP POST request sent from the LINE Platform. For more information, see response in the Messaging API Reference.

Vercel產出的網址是  https://gpt-ai-assistant-h7042oo7f-alans-projects-a5fee1ab.vercel.app

是需要指定 ChatGPT model 嗎?

**Comment by memochou1993** [comment]
Hi

請參考這份文件：

https://memochou1993.github.io/gpt-ai-assistant-docs/questions.html#為什麼-line-平台會出現-404-錯誤

有問題再歡迎提出。

**Comment by wk9480** [comment]
感謝回覆已經打通了只是現在送訊息一直回覆429等了半天再送訊息一樣因為根本沒有使用過幾次ChatGPT搞不懂怎麼會這樣？

Sent from Yahoo Mail on Android 
 
  On Fri, Dec 29, 2023 at 2:01, Memo ***@***.***> wrote:   


Hi

請參考這份文件：

https://memochou1993.github.io/gpt-ai-assistant-docs/questions.html#為什麼-line-平台會出現-404-錯誤

有問題再歡迎提出。

**Comment by memochou1993** [comment]
請檢查一下 OpenAI 是否還有額度喔！

**Comment by wk9480** [comment]
直接使用ChatGPT 是沒問題的但是用bot打過去會回額度使用完了換過API key也一樣

Sent from Yahoo Mail on Android 
 
  On Wed, Jan 3, 2024 at 14:13, Memo ***@***.***> wrote:   


請檢查一下 OpenAI 是否還有額度喔！
