### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by fsjkdlj** [memochou1993/gpt-ai-assistant#309]
團隊們好，我按照步驟實驗，但在Webhook URL後按下verify卻得到圖片結果
<img width="477" alt="未命名" src="https://github.com/memochou1993/gpt-ai-assistant/assets/155517213/ce8d4e59-1138-4a25-b24a-08a11d934a29">

**Comment by memochou1993** [comment]
@fsjkdlj 

重新填一次你的 `LINE_CHANNEL_SECRET` 的值喔！

Ref: https://memochou1993.github.io/gpt-ai-assistant-docs/questions.html#為什麼-line-平台會出現-403-錯誤
