### ISSUE TITLE
無法完整回復對話內容

### ISSUE THREAD

**Issue by ding1018** [memochou1993/gpt-ai-assistant#311]
請問以下的狀況要如何解決呢?
原本以為是Token限制的問題也有加值Open ai的Token，但還是無法讓它完整回覆。

![S__19005444_0](https://github.com/memochou1993/gpt-ai-assistant/assets/115063494/4408d427-9709-494e-8106-0b264e60b7b4)
![S__19005442_0](https://github.com/memochou1993/gpt-ai-assistant/assets/115063494/77551fea-6f22-4a9d-86d5-3b424fbca1d8)
![S__19005445_0](https://github.com/memochou1993/gpt-ai-assistant/assets/115063494/96603198-888c-4b0e-a3d6-e40307d71a0e)

**Comment by memochou1993** [comment]
Hi

請調高 `OPENAI_COMPLETION_MAX_TOKENS` 的值到 128 或更高。

但是如果你沒有 Vercel 的團隊方案，有可能會遇到回應超時的情況。
