### ISSUE TITLE
429 - Rate limit reached for requests

### ISSUE THREAD

**Issue by yujieChen0924** [memochou1993/gpt-ai-assistant#313]
您好，除了"缺少環境變數：SERPAPI_API_KEY"，還有出現"Request failed with status code 429"，想請問可以怎麼解決?
(429 - Rate limit reached for requests |
Cause: You are sending requests too quickly.
Solution: Pace your requests. Read the Rate limit guide.)
謝謝!

<img width="916" alt="螢幕擷取畫面 2024-01-11 093347" src="https://github.com/memochou1993/gpt-ai-assistant/assets/156255901/89a8d34d-9e3a-4ec7-813c-daa895f92759">

<img width="268" alt="螢幕擷取畫面 2024-01-11 093128" src="https://github.com/memochou1993/gpt-ai-assistant/assets/156255901/dd51f7c4-59ac-452d-8f4f-6457c480cf8a">

429 - Rate limit reached for requests	Cause: You are sending requests too quickly.
Solution: Pace your requests. Read the [Rate limit guide](https://platform.openai.com/docs/guides/rate-limits).

**Comment by memochou1993** [comment]
@yujieChen0924 

嗨，你檢查你的 OpenAI 是否有額度。

然後 SERPAPI_API_KEY 的值，你可以到 https://serpapi.com/ 取得。
