### ISSUE TITLE
Vercel Pro timeout 改成 300 秒

### ISSUE THREAD

**Issue by rickc0811** [memochou1993/gpt-ai-assistant#318]
hi 

請問大大能否把 **vercel pro** 版本的timeout 改長一點呢?

因為pro目前預設15秒 常常會有504問題

[configurable up to 300s](https://vercel.com/docs/functions/configuring-functions/duration)
<br>

<img src="https://github.com/memochou1993/gpt-ai-assistant/assets/125380779/01e956f0-2a8a-4b54-91fa-a7ce41566dc4" width="500" height="400">

**Comment by memochou1993** [comment]
@rickc0811 

嗨，幫我升到 4.8.1 看看。

因為我沒有用過 Pro 方案，所以還需要請你幫忙嘗試一下

謝謝。

**Comment by rickc0811** [comment]
謝謝你 改成300 可以正常始用了
