### ISSUE TITLE
改串 gpt-4 模型

### ISSUE THREAD

**Issue by classup101** [memochou1993/gpt-ai-assistant#322]
因為想要訓練ai,讓這個line帳號可以回答一些專門的問題,但是3.5沒有訓練的功能,想請問您知不知道直接改串4的api能不能有效運用?

如果可以訓練的話,不同用戶加入此line帳號為好友,每個人開啟的對話是否可以讀取到初始訓練內容?

**Comment by memochou1993** [comment]
你已經有自己的 fine-tunned 模型了嗎？

你可以這樣用：

修改 Vercel 的環境變數：

```
OPENAI_COMPLETION_MODEL=ft:gpt-3.5-turbo:my-org:custom_suffix:id
```
