### ISSUE TITLE
Request failed with status code 401

### ISSUE THREAD

**Issue by YUUN0424** [memochou1993/gpt-ai-assistant#331]
![1716221362479](https://github.com/memochou1993/gpt-ai-assistant/assets/170249586/809637b2-3371-4787-a93c-6dff70f2a110)
可以執行畫出圖片但不能執行文字問答
確認API KEY正確
有修改可以新增DELL-3的程式碼
請問打x的部分是取消修改嗎?

**Comment by memochou1993** [comment]
@YUUN0424 

它寫 api key 是 `null`，可以再重新部署，並檢查環境變數 `OPENAI_API_KEY` 是否有值嗎？
