### ISSUE TITLE
想請問使用 gpt-4o 圖片讀取與產生

### ISSUE THREAD

**Issue by tsopk45168** [memochou1993/gpt-ai-assistant#334]
開發者您好
目前我使用的版本是4.8.3
環境變數除了line、openai以外
只有添加OPENAI_COMPLETION_MODEL為gpt-4o
但是沒辦法像issues、PR談到的這樣進行直接讀取影像內容或產生圖片
想請問是哪方面需要進行設定呢?
謝謝

**Comment by memochou1993** [comment]
@tsopk45168 

嗨！請升到 `v4.9.0` 就可以讀取圖片囉！

**Comment by wellimean** [comment]
請問如何升級版本?
