### ISSUE TITLE
回覆 429 錯誤訊息，畫面不是顯示 ok 資訊

### ISSUE THREAD

**Issue by MaoKaiSue** [memochou1993/gpt-ai-assistant#335]
問題1-請問line詢問問題,一直回覆429錯誤訊息如下,但已經有設定api key以及重新佈署了
POST https://api.openai.com/v1/chat/completions
Request failed with status code 429
You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
![429錯誤訊息](https://github.com/memochou1993/gpt-ai-assistant/assets/173022903/30db46db-d6fa-429b-aa75-c6fdb694f1d0)

問題2.vercel平台Project畫面不是顯示ok資訊的問題
Project不是顯示ok而是顯示下方訊息
{"currentVersion":"4.8.3","latestVersion":"4.8.3"}
![vercelProject](https://github.com/memochou1993/gpt-ai-assistant/assets/173022903/2de6cedf-373d-43d0-9b27-01c540c344d7)

上列兩個問題再請大大協助釋疑,非常感謝

**Comment by Hsiu2023** [comment]
我也碰到這個問題 要怎麼解決?

**Comment by memochou1993** [comment]
@MaoKaiSue 

你有在 OpenAI 儲值嗎？

第二個畫面是正常的。

**Comment by Hsiu2023** [comment]
我搞定了 花了一點錢儲值...
果然是額度不夠
