### ISSUE TITLE
請問可以串接 Fine-tuning 過的模型或是 Assistants API 嗎

### ISSUE THREAD

**Issue by GGUapi** [memochou1993/gpt-ai-assistant#337]
開發者您好~
如題
我有在我的GPT新增一個Assistants API基於GPT-4o客製化一個模型
請問我可以利用這個Gitnub將訓練好的模型跟Line做串接嗎
如果可以的話 麻煩教我怎麼做
謝謝您!

**Comment by memochou1993** [comment]
@GGUapi 

試試看這樣有沒有用！？

修改成你的 model 名稱：

```
OPENAI_COMPLETION_MODEL=ft:gpt-3.5-turbo:my-org:custom_suffix:id
```

Ref: https://github.com/memochou1993/gpt-ai-assistant/issues/298

**Comment by GGUapi** [comment]
如果我是使用assistants的方式呢
我的assistant是基於4o去做的
![1720662034492](https://github.com/memochou1993/gpt-ai-assistant/assets/43565919/3b1f2718-45f4-43b5-89a7-92449e32551c)

**Comment by GGUapi** [comment]
您好 所以目前是無法使用 Assistants API嗎
因為有翻到之前有人提問 有看到您說不行
不知道是以後沒有打算支援此API嗎

**Comment by memochou1993** [comment]
目前沒有～
