### ISSUE TITLE
Line 機器人部分沒有回應

### ISSUE THREAD

**Issue by jhenyuwu** [memochou1993/gpt-ai-assistant#338]
![image](https://github.com/user-attachments/assets/41d33ddc-7e66-43cf-ad4e-484966ee3345)
![image](https://github.com/user-attachments/assets/11a22c6f-28c5-44a9-89bb-609427eed01a)

已經加了vercil_cli_version 也不行

有沒有其他地方可以看錯誤資訊呢?

**Comment by memochou1993** [comment]
@jhenyuwu 可能是打錯字了吧，把所有環境變數重新填一次，確認不要有空白。

**Comment by WalterC1029** [comment]
![error](https://github.com/user-attachments/assets/47fd7395-3fdb-4d34-9787-bec76f7fdb80)
我也有一樣的問題！

**Comment by memochou1993** [comment]
@WalterC1029 

https://memochou1993.github.io/gpt-ai-assistant-docs/questions.html#為什麼-line-平台會出現-404-錯誤

**Comment by WalterC1029** [comment]
![webhook](https://github.com/user-attachments/assets/379af147-24a8-405e-9ef8-e21498843f1e)

**Comment by WalterC1029** [comment]
![Production](https://github.com/user-attachments/assets/b0927702-c107-4459-b2e9-ffb5981d55d2)
