### ISSUE TITLE
上下文訊息與 tokens 設定 24 與 2048 輸出訊息還是很短

### ISSUE THREAD

**Issue by sevaroy** [memochou1993/gpt-ai-assistant#339]
<img width="666" alt="image" src="https://github.com/user-attachments/assets/fd78e361-deae-4fd9-b391-0df636df863a">

**Comment by memochou1993** [comment]
@sevaroy 

可以調整 `OPENAI_COMPLETION_MAX_TOKENS` 看看喔！

記得重新部署！
