### ISSUE TITLE
頻繁出現 429 錯誤

### ISSUE THREAD

**Issue by sonychen777** [memochou1993/gpt-ai-assistant#342]
您好 ! 我剛剛檢查了我的api key
重整了好幾次還是發現會出問題
![459168683_1042102450728979_5870523395437933197_n](https://github.com/user-attachments/assets/4dfce8be-f8ef-430a-bf4a-5da5e7678c8c)
![459229652_3846590938957870_3510848912223374730_n](https://github.com/user-attachments/assets/cbf5635c-8d5b-4117-aa4f-9f762a3b6591)

**Comment by memochou1993** [comment]
@sonychen777 

OpenAI 有儲值嗎？
