### ISSUE TITLE
Log 中的 404 有影響嗎？

### ISSUE THREAD

**Issue by chutwei** [memochou1993/gpt-ai-assistant#344]
![Screenshot 2024-10-03 013957](https://github.com/user-attachments/assets/10a0e510-e190-40d5-a60e-04f1c8e6c016)
需要擔心嗎?
還有就是小助手回答時 有字元限制 可以修改嗎?
謝謝

**Comment by memochou1993** [comment]
@chutwei 

畫面中出現的 404 不影響

使用 `OPENAI_COMPLETION_MAX_TOKENS` 改變字數哦，但是很容易超時就不回應了

https://memochou1993.github.io/gpt-ai-assistant-docs/environments.html#一覽
