### ISSUE TITLE
About 400 bad request

### ISSUE THREAD

**Issue by slill314** [memochou1993/gpt-ai-assistant#345]
您好，我是一位自己在拼湊軟體的初學者
在https://memochou1993.github.io/gpt-ai-assistant-docs/ 拜讀您的作品後，實作您的專案
目前有成功部署在vercel上，想請問您

有時候太久沒使用，久久呼叫一次時，vercel感覺會像休眠(可能不是真的休眠)無回應
但同一句話再次詢問就會有反應，到log看，會發現 在line上明明都是同一句話

但是有時候會是400 bad request、有時候卻又成功 200 OK

所以想請問看看大神是否知道原因? 

謝謝您的閱讀，若能知道原因的話就更好了!

![PSOT_400_20241009](https://github.com/user-attachments/assets/78254752-763f-4980-b6df-a732377c9784)

**Comment by memochou1993** [comment]
應該是 Vercel 超時了，免費方案有 10 秒限制

目前除了訂閱 Vercel 之外，可能沒辦法解決這個問題
