### ISSUE TITLE
關於機器人的暱稱和語氣

### ISSUE THREAD

**Issue by ShuKaiHu** [memochou1993/gpt-ai-assistant#346]
開發者好, 

謝謝你開發這麼有趣的程式, 
我在測試使用的過程中, 想要針對不同人是有不同的回應, 
目前可以用prompt粗略解決這需求, 

但還是會受限於
ex1: 得設計機器人得誘導對方講出名字 => 干擾使用體驗
ex2: 無法有效辨識對方是不是真的為"名字是小明"的人

想問看看有沒有機會用line ID或是暱稱來進行區別是待遇.
如果可以設定族群那就太好了
ex: 把對話對象分成三類, 
淺在客戶 => 用心對待, 非淺在客戶 => 隨便對待, 未知 => 探索資訊

非常謝謝開發者大大!
SKHU

**Comment by memochou1993** [comment]
@ShuKaiHu 

可以用 `BOT_NAME` 和 `BOT_TONE` 環境變數

請參考文件：

https://memochou1993.github.io/gpt-ai-assistant-docs/environments.html#一覽
https://memochou1993.github.io/gpt-ai-assistant-docs/recipes.html
