### ISSUE TITLE
對話中會出現機器人沒有回覆的狀況

### ISSUE THREAD

**Issue by dfgh012316** [memochou1993/gpt-ai-assistant#4]
**Describe the bug**

在某些情況下，機器人會沒有辦法回應訊息。
而不是 [我無法回答您的問題。但是如果你有任何其他問題，我很樂意為你提供服務]

**To Reproduce**

不確定何種情況下會出現無法回應的問題。

**Expected behavior**

針對沒有辦法回應的情況，回應[我無法回答你的問題，因為 "{例外狀況}"]

**Screenshots**
無法回應的狀況，但當時沒有截到 Vercel 的 Log
![LINE_capture_692517994 638557](https://user-images.githubusercontent.com/24380879/206972256-6bc1fda0-7ed0-4ed9-a317-49cc64937e13.jpeg)

嘗試重現無法回應的狀況
![095DFDE9-A75A-4099-B6E0-52A4140B6136](https://user-images.githubusercontent.com/24380879/206973422-b6ae4e41-dec7-4ba6-a7d6-037d90702e11.jpeg)

此時 Vercel 的 Log
![截圖 2022-12-12 下午2 13 00](https://user-images.githubusercontent.com/24380879/206973616-eb18f701-73ce-4d76-b44a-3963b63133f5.png)

**Additional context**
過往使用 ngrok 或是 heroku部署發生類似的情況都是太久沒有使用導致伺服器端需要喚醒，在喚醒的過程中沒有辦法順利回應。但這次是在對話的過程中突然中斷無法回應，猜測是取得 openAI  API 的 response時出現非預期的情況。

不知道我這邊還能提供哪些資訊可以協助判斷呢?

**Comment by memochou1993** [comment]
@dfgh012316 

感謝回饋！這是已知的問題。

主要原因有兩個：

1. Vercel 的免費方案有 10 秒的超時設定。
2. 得到 AI 長文的回應，又送了大量的上下文到 OpenAI，使 OpenAI 回應超過 10 秒。

有幾種處理方式：

1. 像你說的，發生超時就回「回應超時」之類的訊息。
2. 限縮上下文的字數，目前是 20 則訊息，如果發現總字數太長，就縮減之類的。

不曉得你覺得如何？

**Comment by dfgh012316** [comment]
Hello @memochou1993 

感謝分享! 

我認為可以兩種作法都一起實作，能盡量避免得不到回應的情況萬一還是超時也能得知是因為超時的原因

**Comment by memochou1993** [comment]
@dfgh012316 

嗨！我新增了超時的錯誤訊息和把限縮了上下文訊息數，希望可以改善。

可以幫我 Sync fork 一下，更新程式碼，測測看。

感謝。

**Comment by dfgh012316** [comment]
@memochou1993 

Hello,

I have re-deployed after sync fork 
![截圖 2022-12-12 下午9 32 16](https://user-images.githubusercontent.com/24380879/207058923-f291acf6-0bc7-4625-95a5-5c7080bae657.png)

I try to reproduce the timeout error,but there is still no response.
<img width="375" alt="截圖 2022-12-12 下午9 31 54" src="https://user-images.githubusercontent.com/24380879/207059066-3383336f-c9fb-4ad4-96b2-f0db76754ebe.png">

Vercel Error Log
![截圖 2022-12-12 下午9 31 00](https://user-images.githubusercontent.com/24380879/207059143-7b4582f8-52bd-4582-9119-0e4778f394d1.png)

If there is anything that can help you, please feel free to let me know .

**Comment by memochou1993** [comment]
@dfgh012316 

Hi,

Please sync fork again. I reduce Axios timeout to 9 seconds.

You may also add a `APP_DEBUG` environment to Vercel and redeploy app.

**Comment by dfgh012316** [comment]
@memochou1993 

Hi,

Issues with timeout errors appear to be resolved

Thanks .

**Comment by memochou1993** [comment]
@dfgh012316 

Congrats!
