### ISSUE TITLE
機器人進入群組的召喚功能

### ISSUE THREAD

**Issue by Trinity-SYT-SECURITY** [memochou1993/gpt-ai-assistant#5]
當把這個line bot加入到群組後就，群組成員互相聊天時機器人會一直出現回應，該如何改程式碼，使的機器人直到我們使用者輸入特殊字或是其他呼叫方式才會出現?因為Webhook的影響所以沒法直接更動設定，求解

**Comment by memochou1993** [comment]
@Trinity-SYT-SECURITY 

嗨！

根據指令召喚機器人，這是可以實現的功能。

我再找時間實作一下。

**Comment by Trinity-SYT-SECURITY** [comment]
很感謝您的答覆

**Comment by Grassboy** [comment]
有自己改 code 的權限的話，在 /assistant/assistant.js 的 handleEvent function
`
    if (message.type !== MESSAGE_TYPE_TEXT) return null;
`
的下一行再加一行
`
    if (!message.text.match(/^\/ai /)) return null;
`
應該就只會在聊天訊息是以 `/ai ` 開頭時，才會進行後續處理降子，可以踹踹

**Comment by Trinity-SYT-SECURITY** [comment]
酷~不過我想的是群組功能獨立出來，如果是個人1v1的聊天就不用那麼麻煩

**Comment by Trinity-SYT-SECURITY** [comment]
> 有自己改 code 的權限的話，在 /assistant/assistant.js 的 handleEvent function `if (message.type !== MESSAGE_TYPE_TEXT) return null;` 的下一行再加一行 `if (!message.text.match(/^\/ai /)) return null;` 應該就只會在聊天訊息是以 `/ai ` 開頭時，才會進行後續處理降子，可以踹踹

**Comment by memochou1993** [comment]
怎麼又關掉了XD

我的想法是未來只要輸入指令，就能設定環境變數：

```
SET_BOT_CALL_SIGN=嘿！
```

這個環境變數 `SET_BOT_CALL_SIGN` 決定你想要怎麼呼叫機器人。

一但開啟，你就得必須呼叫機器人才能和他對話，例如：

```
嘿！你好
```

**Comment by memochou1993** [comment]
@Trinity-SYT-SECURITY 

嗨！請參考：https://github.com/memochou1993/gpt-ai-assistant#%E6%8C%87%E4%BB%A4

可以用指令把自動回覆關掉，再用 `ai` 指令呼叫 AI 了！
