### ISSUE TITLE
每次都會回覆都會先回同樣的錯誤訊息

### ISSUE THREAD

**Issue by rockstyle** [memochou1993/gpt-ai-assistant#6]
1.「Auto-reply messages」跟「Greeting messages」的功能沒有關閉的選項
<img width="744" alt="截圖 2022-12-12 17 32 38" src="https://user-images.githubusercontent.com/18436800/207016075-168456c3-2442-488e-af01-fe4799f9a5c0.png">

2.每次都會回覆都會先回同樣的錯誤訊息
<img width="588" alt="截圖 2022-12-12 17 54 25" src="https://user-images.githubusercontent.com/18436800/207016100-e8eb1796-b9a3-470b-955a-8da9bc89e00a.png">

感謝大大

**Comment by memochou1993** [comment]
@rockstyle 

嗨！

在右邊一點的地方，會連過去另一頁，在那一頁可以關掉～

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/38420282/207030714-c1ff9fd6-5d9d-47e9-a6a8-7212474aa2b0.png">

**Comment by memochou1993** [comment]
@rockstyle 

哈哈哈哈哈

恭喜！
