### ISSUE TITLE
有辦法更改生成圖像的大小嗎

### ISSUE THREAD

**Issue by g07377** [memochou1993/gpt-ai-assistant#60]
預設是256X256，這個部分能放進環境變數改大嗎，感謝

**Comment by memochou1993** [comment]
@g07377 

感謝回饋，我也覺得 256x256 有點模糊。

我來加功能。

**Comment by memochou1993** [comment]
@g07377 

完成實作！

幫我更新程式，然後參考文件的「[動態設定](https://github.com/memochou1993/gpt-ai-assistant/blob/main/README.zh.md#%E5%9C%96%E5%83%8F%E7%94%9F%E6%88%90)」這一章節看看。

感謝。

**Comment by g07377** [comment]
是直接在LINE機器人那邊打 /configure IMAGE_GENERATION_SIZE=512x512 這串嗎?
我打了他回我:你可以在設定中設定圖片的分辨率，特別地，你可以將IMAGE_GENERATION_SIZE設定為512x512。
然後發的圖片還是256X256

**Comment by memochou1993** [comment]
@g07377 

幫我用指令確認一下你的應用程式版本是多少？

你可以打「指令」叫出選單。

**Comment by g07377** [comment]
![image](https://user-images.githubusercontent.com/90844147/209436820-5a6e9adb-ea6e-4306-906f-74c82dc45def.png)

**Comment by memochou1993** [comment]
@g07377 

幫我參考「[指令](https://github.com/memochou1993/gpt-ai-assistant/blob/main/README.zh.md#%E6%8C%87%E4%BB%A4)」章節的用法。

**Comment by g07377** [comment]
你想知道我的版本嗎？ 我的版本是1.0. 是這個嗎

**Comment by memochou1993** [comment]
如果你打「指令」呢？

**Comment by g07377** [comment]
沒有 我的沒出現這個，這需要先設定甚麼環境變量才會出現嗎?

**Comment by memochou1993** [comment]
還是你先更新看看原始碼呢？按 Sync Fork 按鈕一下。

**Comment by g07377** [comment]
按了還是不行，跟我的手機本身有關係嗎?

**Comment by memochou1993** [comment]
可以截圖借我看一下嗎？

你的手機是什麼型號的呀？

**Comment by g07377** [comment]
![Screenshot_20221224-214626845](https://user-images.githubusercontent.com/90844147/209438703-cd34f791-2082-413b-aa1f-5be716756f10.jpg)

手機是zenfone7，安卓機

**Comment by memochou1993** [comment]
試試看只有打「Command」呢？

**Comment by g07377** [comment]
NO,一樣不行

**Comment by memochou1993** [comment]
好，試試另一個方法。

幫我到 Vercel 看一下環境變數，有沒有 APP_STORAGE，把值貼上來看一下。

**Comment by g07377** [comment]
Project Settings裡面的Environment Variables嗎，我沒有設定這個，

**Comment by memochou1993** [comment]
先幫我到 [Tokens](https://vercel.com/account/tokens) 這一頁，生成一個 Vercel 的 Key。

<img width="974" alt="image" src="https://user-images.githubusercontent.com/38420282/209440263-84c494d0-f10b-4f65-8f59-6a90a8218b61.png">

然後新增一個環境變數叫 `VERCEL_ACCESS_TOKEN`，值填剛剛生成的 Vercel 的 Key：

<img width="557" alt="image" src="https://user-images.githubusercontent.com/38420282/209440279-ebf75e47-1a17-4773-95a8-f98c733e2578.png">

最後再設定一個環境變數叫 `APP_STORAGE`，值填以下這樣：

```
{"IMAGE_GENERATION_SIZE":"256x256"}
```

<img width="937" alt="image" src="https://user-images.githubusercontent.com/38420282/209440218-c0bfca75-e5c3-4c08-9edb-3fb8c39f8bda.png">

**Comment by g07377** [comment]
![未命名](https://user-images.githubusercontent.com/90844147/209441310-64955606-8155-482e-acfe-170e0a7f663c.png)

我直接填了512x512，重新部署後，目前機器人回的圖片還是256x256

**Comment by memochou1993** [comment]
這真的太奇怪了

我想知道你的應用程式現在接受哪些指令...可以幫我都試試看嗎

```
Command
command
/command
指令
/version
版本
Version
version
```

**Comment by g07377** [comment]
![image](https://user-images.githubusercontent.com/90844147/209442545-28ed7ef6-598a-49d8-ac96-a9c78695924c.png)

看起來只有draw <> 正常運行，不知道哪邊出問題

**Comment by memochou1993** [comment]
哇！我發現你的 `version` 指令有用！

你的版本不知為何停留在 `1.5.0`，要不要試著重新把專案 import 進 Vercel 一次呀？

**Comment by g07377** [comment]
有了!成功了，重新import那些指令就都可以了，包含改圖像的指令也成功運行了，感謝!!

**Comment by memochou1993** [comment]
太好了！

不好意思這個指令比較複雜哈哈，為了動態調整設定，做了比較特別的設計。

有想到特別的功能，歡迎再提出來～

🙌 🙌 🙌

**Comment by memochou1993** [comment]
@g07377 

Hi

如果你還有繼續更新程式，請參考用[環境變數](https://github.com/memochou1993/gpt-ai-assistant/blob/main/README.zh.md#%E7%92%B0%E5%A2%83%E8%AE%8A%E6%95%B8)的方式來修改尺寸，比較簡單一點。

原本的方法棄用了。
