### ISSUE TITLE
LINE MessageAPI verify err

### ISSUE THREAD

**Issue by 208417138** [memochou1993/gpt-ai-assistant#69]
Show 404

**Comment by memochou1993** [comment]
@208417138 

Hi,

Pls provide some screenshots for debugging.

**Comment by 208417138** [comment]
> @208417138 
> 
> 
> 
> Hi,
> 
> 
> 
> Pls provide some screenshots for debugging.

![image](https://user-images.githubusercontent.com/72386132/209361738-480a4088-1869-4513-ba11-6fecfefe7ca0.png)

Thank you.

**Comment by memochou1993** [comment]
@208417138 

Hi

Check webhook URL must has be a `/webhook` suffix.

**Comment by 208417138** [comment]
> suffix

![image](https://user-images.githubusercontent.com/72386132/209375115-df093732-7305-4019-8c90-81c09c6bbba9.png)

**Comment by 208417138** [comment]
> @208417138 
> 
> 
> 
> Hi
> 
> 
> 
> Please check the webhook URL must have a `/webhook` suffix.

Ok, I got it thanks a lot

**Comment by memochou1993** [comment]
@208417138 

Hope you succeed!
