### ISSUE TITLE
Concerning the GPT model 

### ISSUE THREAD

**Issue by Zero6992** [memochou1993/gpt-ai-assistant#7]
It seems that this chatbot is based on the GPT-3 model's API, not the GPT-3.5 model used by chatGPT

 I know that there is no official GPT-3.5 API available now

But there are some unofficial APIs that can be used, what are your thoughts on this?

**Comment by memochou1993** [comment]
@Zero6992 

Hi, I saw you project! That's really cool!

Could you provide some reference about unofficial APIs or repo which implemented.

Maybe we can built some experimental features.

**Comment by memochou1993** [comment]
@Zero6992 

Hi, I notice that OpenAI has add Cloudflare protection.

Is there any way to use ChatGPT conversion API now?

**Comment by memochou1993** [comment]
@Zero6992 

Thanks for the refs.

It seems like still unstable and response takes long time.

Close this issue.
