### ISSUE TITLE
Webhook 問題

### ISSUE THREAD

**Issue by Johnson1223** [memochou1993/gpt-ai-assistant#9]
![螢幕擷取畫面 2022-12-13 012152](https://user-images.githubusercontent.com/91715772/207111675-928ffd74-edb5-4ca8-9a50-b4f64a3a4534.png)
你好:照著步驟安裝在verify時出現此error該如何解決，謝謝

**Comment by memochou1993** [comment]
@Johnson1223 

嗨！請幫我檢查是否有 `/webhook` 後綴。

**Comment by Johnson1223** [comment]
> @memochou1993 

加上已成功了，謝謝

**Comment by memochou1993** [comment]
@Johnson1223 

很棒！
