### ISSUE TITLE
upgrade後版本還是1.0

### ISSUE THREAD

**Issue by andy910389** [memochou1993/gpt-ai-assistant#92]
版主你好
目前聊天機器人的運作都很正常
然後輸入version後顯示1.0
但是按照更新流程
在我自己的gpt-ai-assistant project中
按下"Sync Fork" 然後點選Up branch
然後更新完按鍵會變成灰色
https://imgur.com/a/St29oua

接著登出line 再重新登入
輸入version後
結果卻變成0.9.2 
https://imgur.com/a/85IaERB

然後我輸入 "版本"
會顯示1.11.0
https://imgur.com/a/jmxgmyL
中英文的版本好像都不太一樣

**Comment by andy910389** [comment]
已解決 謝謝

**Comment by memochou1993** [comment]
@andy910389 

嗨！

可以用 `/version` 或「版本」指令！

你有更新成功！
