### ISSUE TITLE
發圖片

### ISSUE THREAD

**Issue by MLChen** [memochou1993/gpt-ai-assistant#97]
只要有人發圖片就會報錯

Cannot read properties of undefined (reading 'replaceAll')

Method: null
Host: null
Path: null
Code: null
Message: null

**Comment by memochou1993** [comment]
@MLChen 

感謝回報！

**Comment by memochou1993** [comment]
@MLChen 

已修正，請幫我更新到 v1.12.1 版！

謝謝。
